contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 7af70a31-8fee-433a-834f-95c85d52c4f5
inputs: []
name: Alex Scratchpad
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fb85cf1f-8400-4113-84c8-5cea912550eb
      iscommand: false
      name: ""
      version: -1
    taskid: fb85cf1f-8400-4113-84c8-5cea912550eb
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: -emailthreads:""
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Searches Demisto incidents.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: c786ab81-4f92-4279-8883-c332a6805739
      iscommand: false
      name: Set Time
      script: SearchIncidentsV2
      type: regular
      version: -1
    taskid: c786ab81-4f92-4279-8883-c332a6805739
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 520,
          "y": 390
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: fd8a046c-f6a0-433e-876d-8bd2b631ef10
      iscommand: false
      name: Alex Test
      playbookId: cdd39cb3-58e1-4993-82f2-8fd6c20f98b6
      type: playbook
      version: -1
    taskid: fd8a046c-f6a0-433e-876d-8bd2b631ef10
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 520,
          "y": 570
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 615,
        "width": 450,
        "x": 450,
        "y": 50
      }
    }
  }
