contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.1.0
    itemVersion: 1.0.1
    packID: Change_Management
    packName: Change Management
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook guides the user in the process of editing an existing policy.
  The playbook sends a data collection form to retrieve the relevant parameters for
  editing the existing rule.
id: PAN-OS edit policy
inputs:
- description: The email of the relevant security team for firewall change management
    approval.
  key: SecurityTeamEmail
  playbookInputQuery: null
  required: false
  value: {}
- description: The name of the relevant policy.
  key: rulename
  playbookInputQuery: null
  required: false
  value: {}
name: PAN-OS edit policy
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fa6a958b-44d3-4166-885e-674d09d7f16c
      iscommand: false
      name: ""
      version: -1
    taskid: fa6a958b-44d3-4166-885e-674d09d7f16c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": -280
        }
      }
  "1":
    continueonerrortype: ""
    form:
      description: Please provide the following parameters.
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Element to change?
        options: []
        optionsarg:
        - simple: source
        - simple: destination
        - simple: application
        - simple: action
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: singleSelect
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "1"
        label: ""
        labelarg:
          simple: Element value to be edit.
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: shortText
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "2"
        label: ""
        labelarg:
          simple: Rule position. (Should be the exact position as defined in Panorama.)
        options: []
        optionsarg:
        - simple: post-rulebase
        - simple: pre-rulebase
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: singleSelect
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "3"
        label: ""
        labelarg:
          simple: Behavior
        options: []
        optionsarg:
        - simple: replace
        - simple: add
        - simple: remove
        placeholder: ""
        readonly: false
        required: false
        tooltip: Whether to replace, add, or remove the element_value from the current
          rule object value.
        type: singleSelect
      sender: ""
      title: Which parameters to edit in the policy?
      totalanswers: 0
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Please provide the following parameters for editing the current policy.
      cc: null
      format: ""
      methods:
      - email
      subject:
        simple: Parameters to edit in the policy
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: false
        retriescount: 2
        retriesinterval: 360
      to:
        simple: ${inputs.SecurityTeamEmail}
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This task queries the user about which object to modify in the
        current policy.
      id: 1ebaf0ef-a356-4680-86cc-eb81d6514f81
      iscommand: false
      name: Which parameters to edit in the policy?
      type: collection
      version: -1
    taskid: 1ebaf0ef-a356-4680-86cc-eb81d6514f81
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 300,
          "y": 80
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0bf332bc-2864-43b9-8c0a-a56b17a00036
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 0bf332bc-2864-43b9-8c0a-a56b17a00036
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 40,
          "y": 1060
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      behaviour:
        simple: ${Which parameters to edit in the policy?.Answers.3}
      element_to_change:
        simple: ${Which parameters to edit in the policy?.Answers.0}
      element_value:
        simple: ${Which parameters to edit in the policy?.Answers.1}
      pre_post:
        simple: ${Which parameters to edit in the policy?.Answers.2}
      rulename:
        simple: ${inputs.rulename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Edits a policy rule.
      id: 4c4448c3-5c73-403c-8f27-3bfd8d6a9f8f
      iscommand: true
      name: Edit current policy
      script: '|||pan-os-edit-rule'
      type: regular
      version: -1
    taskid: 4c4448c3-5c73-403c-8f27-3bfd8d6a9f8f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 300,
          "y": 275
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: Commit the PAN-OS/Panorama Firewall configuration.\nIf specified
        as Panorama, it also pushes the policies to the specified device group in
        the instance.
      id: 97f707a9-2681-45e9-8d89-f5c137e452aa
      iscommand: false
      name: PAN-OS Commit Configuration
      playbookId: PAN-OS Commit Configuration
      type: playbook
      version: -1
    taskid: 97f707a9-2681-45e9-8d89-f5c137e452aa
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -200,
          "y": 680
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      behaviour:
        simple: ${Which parameters to edit in the policy?.Answers.2}
      element_to_change:
        simple: ${Which parameters to edit in the policy?.Answers.0}
      element_value:
        simple: ${Which parameters to edit in the policy?.Answers.1}
      rulename:
        simple: ${inputs.rulename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Edits a policy rule.
      id: 16ea8049-c1ef-4542-89fa-30e5df14db4f
      iscommand: true
      name: Edit current policy
      script: '|||pan-os-edit-rule'
      type: regular
      version: -1
    taskid: 16ea8049-c1ef-4542-89fa-30e5df14db4f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -200,
          "y": 275
        }
      }
  "10":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.name
                    operator: containsGeneral
                    right:
                      value:
                        simple: Panorama
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
          right:
            value: {}
      label: panorama
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.name
                    operator: containsGeneral
                    right:
                      value:
                        simple: Pan-os
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: Pan-os
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      Pan-os:
      - "11"
      panorama:
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Which instance is available - Panorama or PAN-OS? '
      id: e884484a-7226-4a09-8833-bdef0f6ec1c9
      iscommand: false
      name: Panorama or PAN-OS?
      type: condition
      version: -1
    taskid: e884484a-7226-4a09-8833-bdef0f6ec1c9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": -130
        }
      }
  "11":
    continueonerrortype: ""
    form:
      description: Please provide the following parameters.
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Element to change?
        options: []
        optionsarg:
        - simple: source
        - simple: destination
        - simple: application
        - simple: action
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: singleSelect
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "1"
        label: ""
        labelarg:
          simple: Element value to be edit.
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: Please provide a value for the element.
        type: shortText
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "2"
        label: ""
        labelarg:
          simple: Behavior
        options: []
        optionsarg:
        - simple: replace
        - simple: add
        - simple: remove
        placeholder: ""
        readonly: false
        required: false
        tooltip: Whether to replace, add, or remove the element_value from the current
          rule object value.
        type: singleSelect
      sender: ""
      title: Which parameters to edit in the policy?
      totalanswers: 0
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Please provide the following parameters for editing the current policy.
      cc: null
      format: ""
      methods:
      - email
      subject:
        simple: Parameters to edit in the policy
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: false
        retriescount: 2
        retriesinterval: 360
      to:
        simple: ${inputs.SecurityTeamEmail}
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This task queries the user about which object to modify in the
        current policy.
      id: d0b934cc-37de-4c3e-8aef-7dcd6e1aa29a
      iscommand: false
      name: Which parameters to edit in the policy?
      type: collection
      version: -1
    taskid: d0b934cc-37de-4c3e-8aef-7dcd6e1aa29a
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": -200,
          "y": 80
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
      subplaybook:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: fe262bcb-ebcc-4e3a-88c3-4d76bfa7d108
      iscommand: false
      name: 'Delete Context '
      script: DeleteContext
      type: regular
      version: -1
    taskid: fe262bcb-ebcc-4e3a-88c3-4d76bfa7d108
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": 870
        }
      }
  "13":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Panorama.SecurityRule
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Was the rule modified?
      id: c1495577-e895-4009-8aa9-28f1096fc62d
      iscommand: false
      name: 'Was the rule modified? '
      type: condition
      version: -1
    taskid: c1495577-e895-4009-8aa9-28f1096fc62d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 470
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Rule wasn't edited. Please verify inputs.
      id: 69d27a21-a0c2-4f85-8bb7-7c86c909b92c
      iscommand: false
      name: Rule wasn't edited. Please verify inputs.
      type: regular
      version: -1
    taskid: 69d27a21-a0c2-4f85-8bb7-7c86c909b92c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 290,
          "y": 680
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "10_11_Pan-os": 0.64,
      "13_6_yes": 0.77
    },
    "paper": {
      "dimensions": {
        "height": 1405,
        "width": 880,
        "x": -200,
        "y": -280
      }
    }
  }
