contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.5.0
    itemVersion: 1.0.8
    packID: CiscoStealthwatch
    packName: Cisco Secure Network Analytics (Stealthwatch)
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  This playbook blocks domains using Cisco Stealthwatch.
  The playbook checks whether the Cisco Stealthwatch integration is enabled, whether the Domain input has been provided and if so, blocks the domain.
id: Block Domain - Cisco Stealthwatch
inputs:
- description: The Domain to block.
  key: Domain
  playbookInputQuery: null
  required: false
  value: {}
name: Block Domain - Cisco Stealthwatch
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b124cfe7-a56f-4490-880b-78cf3274b99b
      iscommand: false
      name: ""
      version: -1
    taskid: b124cfe7-a56f-4490-880b-78cf3274b99b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -100
        }
      }
  "2":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Stealthwatch Cloud
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: Active
                root: modules
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Verify that there is a valid instance of Check Point Firewall enabled.
      id: 1268fa81-6e6d-4d75-8f22-f6893af3cb9c
      iscommand: false
      name: Is Cisco Stealthwatch enabled?
      type: condition
      version: -1
    taskid: 1268fa81-6e6d-4d75-8f22-f6893af3cb9c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 250
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      domain:
        complex:
          root: inputs.Domain
    separatecontext: false
    skipunavailable: false
    task:
      brand: Stealthwatch Cloud
      description: Add a domain or IP to the block list
      id: 951938f0-4b63-46e8-8fdc-7e6a26bbf853
      iscommand: true
      name: Block Domain
      script: Stealthwatch Cloud|||sw-block-domain-or-ip
      type: regular
      version: -1
    taskid: 951938f0-4b63-46e8-8fdc-7e6a26bbf853
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 430
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 897a00db-2a04-48d5-8630-e55b5443f0b9
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 897a00db-2a04-48d5-8630-e55b5443f0b9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 600
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Domain
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the necessary inputs were provided
      id: cfdef7e9-5188-4715-8a20-4cf22f75f1ee
      iscommand: false
      name: Check if Domain input was provided
      type: condition
      version: -1
    taskid: cfdef7e9-5188-4715-8a20-4cf22f75f1ee
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 40
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "2_3_yes": 0.53,
      "2_4_#default#": 0.27,
      "5_2_yes": 0.61,
      "5_4_#default#": 0.77
    },
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 380,
        "x": 450,
        "y": -100
      }
    }
  }
