contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 1.0.2
    packID: WindowsForensics
    packName: Windows Forensics
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook enables gathering forensic data from a host and analyzing
  the acquired data by using the relevant forensics automations.
id: Acquire And Analyze Host Forensics
inputs:
- description: 'A single hostname or IP address from which to acquire the forensic
    data. For example, testpc01. '
  key: Host
  playbookInputQuery: null
  required: false
  value: {}
name: Acquire And Analyze Host Forensics
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 00a4be27-1ca3-497d-8100-3c001c8fab2c
      iscommand: false
      name: ""
      version: -1
    taskid: 00a4be27-1ca3-497d-8100-3c001c8fab2c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 270,
          "y": -170
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      GetMft:
        simple: "true"
      GetNetworkTraffic:
        simple: "true"
      GetRegistry:
        simple: "true"
      Host:
        simple: ${inputs.Host}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: This playbook allows the user to gather multiple forensic data
        from a Windows endpoint, including network traffic, MFT (Master File Table),
        and registry export, by using the PS remote automations that enable you to
        connect to a Windows host using just the native Windows management tools.
        You do not need to install any 3rd-party tools.
      id: e31fb2e3-3dc8-4099-8e7e-2bf07e1f3e52
      iscommand: false
      name: PS-Remote Acquire Host Forensics
      playbookId: PS-Remote Acquire Host Forensics
      type: playbook
      version: -1
    taskid: e31fb2e3-3dc8-4099-8e7e-2bf07e1f3e52
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 500,
          "y": 150
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3fc3264f-288c-4360-8972-d5f648ca6a16
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 3fc3264f-288c-4360-8972-d5f648ca6a16
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 270,
          "y": 500
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      PcapEntryID:
        simple: ${PcapDetails.EntryID}
      RegistryEntryId:
        simple: ${RegistryDetails.EntryID}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: This playbook allows the user to analyze forensic evidence acquired
        from a host, such as registry files, memory dump files, and PCAP files.
      id: abaccea2-7642-47dc-835d-202c037abb96
      iscommand: false
      name: Forensics Tools Analysis
      playbookId: Forensics Tools Analysis
      type: playbook
      version: -1
    taskid: abaccea2-7642-47dc-835d-202c037abb96
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 500,
          "y": 320
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Host
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 149d44c0-a825-4db0-89ae-57d23251de85
      iscommand: false
      name: Was a hostname provided?
      type: condition
      version: -1
    taskid: 149d44c0-a825-4db0-89ae-57d23251de85
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 270,
          "y": -30
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 590,
        "x": 270,
        "y": -170
      }
    }
  }
