contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.5.0
    itemVersion: 1.0.8
    packID: CiscoStealthwatch
    packName: Cisco Secure Network Analytics (Stealthwatch)
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook lists security events and returns the results to the context.
id: List Cisco Stealthwatch Security Events
inputs:
- description: The amount of time to wait before a timeout occurs (in minutes).
  key: timeout
  playbookInputQuery: null
  required: false
  value:
    simple: "600"
- description: Polling frequency - how often the polling command should run (in minutes).
  key: interval
  playbookInputQuery: null
  required: false
  value:
    simple: "1"
- description: Range of results to return (e.g., 0-20).
  key: range
  playbookInputQuery: null
  required: false
  value:
    simple: 0-20
- description: Tenant ID represents the domain on Cisco Stealthwatch.
  key: tenant_id
  playbookInputQuery: null
  required: true
  value:
    simple: "102"
- description: ""
  key: time_range
  playbookInputQuery: null
  required: true
  value:
    simple: 1 month ago
name: List Cisco Stealthwatch Security Events
outputs:
- contextPath: CiscoStealthwatch.SecurityEventResults
  description: The results of the search.
sourceplaybookid: QRadarFullSearch
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Start of playbook
      id: 230a5fa5-ffb2-4d27-857f-647083ec27dc
      iscommand: false
      name: ""
      version: -1
    taskid: 230a5fa5-ffb2-4d27-857f-647083ec27dc
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: tenant_id
      AdditionalPollingCommandArgValues:
        simple: ${inputs.tenant_id}
      Ids:
        simple: ${CiscoStealthwatch.SecurityEventStatus.id}
      Interval:
        simple: ${inputs.interval}
      PollingCommandArgName:
        simple: search_id
      PollingCommandName:
        simple: cisco-stealthwatch-list-security-events-status
      Timeout:
        simple: ${inputs.timeout}
      dt:
        simple: CiscoStealthwatch.SecurityEventStatus(val.percentComplete.indexof('100')==0).id
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:
        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 75b286fc-4477-4267-8a03-a79de51db5aa
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 75b286fc-4477-4267-8a03-a79de51db5aa
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Playbook is done.
      id: 172877e1-d636-4b2a-8b3e-70dddf7ea585
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 172877e1-d636-4b2a-8b3e-70dddf7ea585
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: CiscoStealthwatch.SecurityEventStatus.percentComplete
          operator: startWith
          right:
            value:
              simple: "100"
      label: "yes"
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether the search is completed.
      id: a8b2bf9c-7b4a-41a8-8a4f-ee76977ba683
      iscommand: false
      name: Is search completed?
      type: condition
      version: -1
    taskid: a8b2bf9c-7b4a-41a8-8a4f-ee76977ba683
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 505
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      tenant_id:
        simple: ${inputs.tenant_id}
      time_range:
        simple: ${inputs.time_range}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cisco Stealthwatch
      description: Initialize listing security events for a domain (called Tenant
        on the API).
      id: 6d2099c6-fc03-418b-8d99-63e20e848d50
      iscommand: true
      name: cisco-stealthwatch-list-security-events-initialize
      script: Cisco Stealthwatch|||cisco-stealthwatch-list-security-events-initialize
      type: regular
      version: -1
    taskid: 6d2099c6-fc03-418b-8d99-63e20e848d50
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 190
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      search_id:
        simple: ${CiscoStealthwatch.SecurityEventStatus.id}
      tenant_id:
        simple: ${inputs.tenant_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cisco Stealthwatch
      description: List security events status.
      id: f47572d3-fd0c-4b51-86c1-3db195ff12af
      iscommand: true
      name: cisco-stealthwatch-list-security-events-status
      script: Cisco Stealthwatch|||cisco-stealthwatch-list-security-events-status
      type: regular
      version: -1
    taskid: f47572d3-fd0c-4b51-86c1-3db195ff12af
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 340
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      limit:
        simple: "5"
      search_id:
        simple: ${CiscoStealthwatch.SecurityEventStatus.id}
      tenant_id:
        simple: ${inputs.tenant_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cisco Stealthwatch
      description: List security events results. Use this command after the search
        job completes.
      id: bbe619ad-2f54-44a1-8a9f-73007aa0fe83
      iscommand: true
      name: cisco-stealthwatch-list-security-events-results
      script: Cisco Stealthwatch|||cisco-stealthwatch-list-security-events-results
      type: regular
      version: -1
    taskid: bbe619ad-2f54-44a1-8a9f-73007aa0fe83
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 890
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1085,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
