contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 1.0.2
    packID: WindowsForensics
    packName: Windows Forensics
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook leverages the RegistryParse automation to perform registry
  analysis and extract forensic artifacts.  The automation includes common registry
  objects to extract which are useful for analyzing registry, or a user provides registry
  path to parse.
id: Registry Parse Data Analysis
inputs:
- description: The entry ID for the registry file to parse.
  key: RegistryFileEntryID
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    The data to parse out of the registry and output to context, including
    Users
    LastLoggedOnUser
    MachineRunOnce
    MachineStartup
    Timezone
    USB
    "All" selects all the options along with any default options.
  key: RegistryData
  playbookInputQuery: null
  required: false
  value: {}
- description: Custom registry path to parse.
  key: CustomRegistryPaths
  playbookInputQuery: null
  required: false
  value: {}
name: Registry Parse Data Analysis
outputs:
- contextPath: RegistryForensicData
  description: The data parsed from the registry.
  type: string
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 77c3cb89-ebc6-40d7-8896-622d033682ee
      iscommand: false
      name: ""
      version: -1
    taskid: 77c3cb89-ebc6-40d7-8896-622d033682ee
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      customRegistryPaths:
        simple: ${inputs.CustomRegistryPaths}
      entryID:
        simple: ${inputs.RegistryFileEntryID}
      registryData:
        simple: ${inputs.RegistryData}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "This command uses the RegistryParse automation to extract critical
        forensics data from a registry file. The essential values are specified by
        the argument. \n"
      id: aa019586-b07e-489f-8d0f-5c60f2362ea8
      iscommand: false
      name: Registry Data parsing
      script: RegistryParse
      tags:
      - RegistryTable
      type: regular
      version: -1
    taskid: aa019586-b07e-489f-8d0f-5c60f2362ea8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 360
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 28499c75-288b-4af0-825e-9658ae301f8b
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 28499c75-288b-4af0-825e-9658ae301f8b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 560
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 435,
        "width": 380,
        "x": 450,
        "y": 190
      }
    }
  }
