contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.5.0
    itemVersion: 2.3.0
    packID: FireEyeHX
    packName: FireEye HX
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  This playbook facilitates threat hunting and detection of IOCs within FireEye Endpoint Security (HX) utilizing three sub-playbooks. The sub-playbooks query FireEye HX for different indicators including files, traffic, and execution flow indicators.

  Note that multiple search values should be separated by commas only (without spaces or any special characters).

  Supported IOCs for this playbook:
  - MD5
  - SHA1
  - SHA256
  - IP Address
  - URLDomain
  - Registry Value
  - Registry Key
  - File Name
  - Process Name
  - Port Number
  - File Path
  - FileType
id: FireEye HX - Indicators Hunting
inputs:
- description: |-
    A single or multiple IP address to search for in FireEye HX logs. Used for both source and destination IP addresses.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: IPAddress
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    A single or multiple port numbers to search for in FireEye HX logs. Used for both remote and local ports.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: PortNumber
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    Single or multiple URLs and/or domains to search for in FireEye HX logs.
    By default, the 'contains' clause is used.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: URLDomain
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    A single or multiple SHA256 file hashes to search for in FireEye HX logs.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: SHA256
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    A single or multiple SHA1 file hashes to search for in FireEye HX logs.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: SHA1
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    A single or multiple MD5 file hashes to search for in FireEye HX logs.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: MD5
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    A single or multiple file paths to search for in FireEye HX logs.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: FilePath
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    A single or multiple file names to search for in FireEye HX logs.
    By default, the 'contains' clause is used.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: FileName
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    A single or multiple file types to search for in FireEye HX logs.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: FileType
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    A single or multiple process names to search for in FireEye HX logs.
    By default, the 'contains' clause is used.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: ProcessName
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    A single or multiple registry keys to search for in FireEye HX logs.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: RegistryKey
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    A single or multiple registry values to search for in FireEye HX logs.
    By default, the 'contains' clause is used.
  key: RegistryValue
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    Single or multiple application names or codes to search for in FireEye HX logs.
    By default, the 'contains' clause is used.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: Application
  playbookInputQuery: null
  required: false
  value: {}
- description: The name of the host set to be searched.
  key: hostSetName
  playbookInputQuery: null
  required: true
  value: {}
- description: |-
    Whether a search is exhaustive.
    Possible values are: yes, no. Default is yes.
  key: exhaustive
  playbookInputQuery: null
  required: false
  value: {}
- description: The interval in seconds between each poll. Default is 60.
  key: interval_in_seconds
  playbookInputQuery: null
  required: false
  value: {}
- description: Limits the results count. (When the limit is reached, the search stops).
  key: limit
  playbookInputQuery: null
  required: false
  value: {}
name: FireEye HX - Indicators Hunting
outputs:
- contextPath: FireEyeHX.HuntingResults
  description: Email message objects and fields that were retrieved from FireEye HX.
  type: string
- contextPath: FireEyeHX.HuntingResults.Timestamp - Event
  description: The timestamp of the event.
  type: number
- contextPath: FireEyeHX.HuntingResults.Timestamp - Accessed
  description: The time when the entry was last accessed.
  type: number
- contextPath: FireEyeHX.HuntingResults.Timestamp - Modified
  description: The time when the entry was last modified.
  type: number
- contextPath: FireEyeHX.HuntingResults.File Name
  description: The name of the file.
  type: string
- contextPath: FireEyeHX.HuntingResults.File Full Path
  description: The full path of the file.
  type: string
- contextPath: FireEyeHX.HuntingResults.DNS Hostname
  description: The name of the DNS host.
  type: string
- contextPath: FireEyeHX.HuntingResults.URL
  description: The event URL.
  type: string
- contextPath: FireEyeHX.HuntingResults.Username
  description: The event username.
  type: string
- contextPath: FireEyeHX.HuntingResults.File MD5 Hash
  description: The MD5 hash of the file.
  type: string
- contextPath: FireEyeHX.HuntingResults.Port
  description: The port.
  type: number
- contextPath: FireEyeHX.HuntingResults.Process ID
  description: The ID of the process.
  type: string
- contextPath: FireEyeHX.HuntingResults.Local IP Address
  description: The local IP address.
  type: string
- contextPath: FireEyeHX.HuntingResults.Local Port
  description: The local port.
  type: number
- contextPath: FireEyeHX.HuntingResults.Remote Port
  description: The remote port.
  type: number
- contextPath: FireEyeHX.HuntingResults.IP Address
  description: The IP address.
  type: string
- contextPath: FireEyeHX.HuntingResults.Process Name
  description: The process name.
  type: string
- contextPath: FireEyeHX.HuntingResults.type
  description: The type of the event.
  type: string
- contextPath: FireEyeHX.HuntingResults.id
  description: The ID of the result.
  type: string
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "32"
      - "33"
      - "34"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a52d8420-7a8c-4987-866d-15dd05511bae
      iscommand: false
      name: ""
      version: -1
    taskid: a52d8420-7a8c-4987-866d-15dd05511bae
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 2720,
          "y": -360
        }
      }
  "31":
    continueonerrortype: ""
    id: "31"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c9a4d741-cb13-4350-8973-b2514b1058e9
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: c9a4d741-cb13-4350-8973-b2514b1058e9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 2720,
          "y": 100
        }
      }
  "32":
    continueonerrortype: ""
    id: "32"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "35"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8dc51aab-477f-4710-8ee1-432a8ac82dce
      iscommand: false
      name: Traffic Indicators
      type: title
      version: -1
    taskid: 8dc51aab-477f-4710-8ee1-432a8ac82dce
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 2290,
          "y": -210
        }
      }
  "33":
    continueonerrortype: ""
    id: "33"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "36"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7137773a-f3ae-4b8d-8880-6d25a5984ce6
      iscommand: false
      name: File Indicators
      type: title
      version: -1
    taskid: 7137773a-f3ae-4b8d-8880-6d25a5984ce6
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 2720,
          "y": -210
        }
      }
  "34":
    continueonerrortype: ""
    id: "34"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "37"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a5bb0ebf-e2af-434c-85b7-fd57b564b859
      iscommand: false
      name: Execution Flow Indicators
      type: title
      version: -1
    taskid: a5bb0ebf-e2af-434c-85b7-fd57b564b859
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 3160,
          "y": -210
        }
      }
  "35":
    continueonerrortype: ""
    id: "35"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "31"
    note: false
    quietmode: 0
    scriptarguments:
      IPAddress:
        complex:
          root: inputs.IPAddress
      PortNumber:
        complex:
          root: inputs.PortNumber
      URLDomain:
        complex:
          root: inputs.URLDomain
      exhaustive:
        simple: "no"
      hostSetName:
        complex:
          root: inputs.hostSetName
      interval_in_seconds:
        complex:
          root: inputs.interval_in_seconds
      limit:
        complex:
          root: inputs.limit
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: e8913685-05b3-4867-8e3a-13c7bcef5e05
      iscommand: false
      name: FireEye HX - Traffic Indicators Hunting
      playbookId: FireEye HX - Traffic Indicators Hunting
      type: playbook
      version: -1
    taskid: e8913685-05b3-4867-8e3a-13c7bcef5e05
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 2290,
          "y": -80
        }
      }
  "36":
    continueonerrortype: ""
    id: "36"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "31"
    note: false
    quietmode: 0
    scriptarguments:
      FileName:
        complex:
          root: inputs.FileName
      FilePath:
        complex:
          root: inputs.FilePath
      FileType:
        complex:
          root: inputs.FileType
      MD5:
        complex:
          root: inputs.MD5
      SHA1:
        complex:
          root: inputs.SHA1
      SHA256:
        complex:
          root: inputs.SHA256
      exhaustive:
        complex:
          root: inputs.exhaustive
      hostSetName:
        complex:
          root: inputs.hostSetName
      interval_in_seconds:
        complex:
          root: inputs.interval_in_seconds
      limit:
        complex:
          root: inputs.limit
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: c5b19104-cea3-4a45-83e7-7b411fd14af9
      iscommand: false
      name: FireEye HX - File Indicators Hunting
      playbookId: FireEye HX - File Indicators Hunting
      type: playbook
      version: -1
    taskid: c5b19104-cea3-4a45-83e7-7b411fd14af9
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 2720,
          "y": -80
        }
      }
  "37":
    continueonerrortype: ""
    id: "37"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "31"
    note: false
    quietmode: 0
    scriptarguments:
      Application:
        complex:
          root: inputs.Application
      HTTPRequestMethods:
        complex:
          root: inputs.HTTPRequestMethods
      ProcessName:
        complex:
          root: inputs.ProcessName
      RegistryKey:
        complex:
          root: inputs.RegistryKey
      RegistryValue:
        complex:
          root: inputs.RegistryValue
      exhaustive:
        complex:
          root: inputs.exhaustive
      hostSetName:
        complex:
          root: inputs.hostSetName
      interval_in_seconds:
        complex:
          root: inputs.interval_in_seconds
      limit:
        complex:
          root: inputs.limit
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: f7373911-d925-42bc-8047-a162f79214db
      iscommand: false
      name: FireEye HX - Execution Flow Indicators Hunting
      playbookId: FireEye HX - Execution Flow Indicators Hunting
      type: playbook
      version: -1
    taskid: f7373911-d925-42bc-8047-a162f79214db
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 3160,
          "y": -80
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 525,
        "width": 1250,
        "x": 2290,
        "y": -360
      }
    }
  }
