contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.5.0
    itemVersion: 1.0.8
    packID: CiscoStealthwatch
    packName: Cisco Secure Network Analytics (Stealthwatch)
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook runs a query on Cisco Stealthwatch flows and return its
  results to the context.
id: Query Cisco Stealthwatch Flows
inputs:
- description: The amount to wait before a timeout occurs (in minutes).
  key: timeout
  playbookInputQuery: null
  required: false
  value:
    simple: "600"
- description: Polling frequency - how often the polling command should run (in minutes).
  key: interval
  playbookInputQuery: null
  required: false
  value:
    simple: "1"
- description: Range of results to return (e.g., 0-20).
  key: range
  playbookInputQuery: null
  required: false
  value:
    simple: 0-20
- description: Tenant ID represents the domain on Cisco Stealthwatch.
  key: tenant_id
  playbookInputQuery: null
  required: true
  value:
    simple: "102"
- description: ""
  key: time_range
  playbookInputQuery: null
  required: true
  value:
    simple: 1 month ago
name: Query Cisco Stealthwatch Flows
outputs:
- contextPath: CiscoStealthwatch.FlowResults
  description: The results of the search.
sourceplaybookid: QRadarFullSearch
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Start of playbook
      id: 230a5fa5-ffb2-4d27-857f-647083ec27dc
      iscommand: false
      name: ""
      version: -1
    taskid: 230a5fa5-ffb2-4d27-857f-647083ec27dc
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: tenant_id
      AdditionalPollingCommandArgValues:
        simple: ${inputs.tenant_id}
      Ids:
        simple: ${CiscoStealthwatch.FlowStatus.id}
      Interval:
        simple: ${inputs.interval}
      PollingCommandArgName:
        simple: search_id
      PollingCommandName:
        simple: cisco-stealthwatch-query-flows-status
      Timeout:
        simple: ${inputs.timeout}
      dt:
        simple: CiscoStealthwatch.FlowStatus(val.percentComplete.indexof('100')==0).id
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:
        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: f0204271-a851-438f-8930-8c2a7f740a3a
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: f0204271-a851-438f-8930-8c2a7f740a3a
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Playbook is done.
      id: 172877e1-d636-4b2a-8b3e-70dddf7ea585
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 172877e1-d636-4b2a-8b3e-70dddf7ea585
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: CiscoStealthwatch.FlowStatus.percentComplete
          operator: startWith
          right:
            value:
              simple: "100"
      label: "yes"
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether the search is completed.
      id: d5413bce-fc23-4193-8f07-af3ecd0393ad
      iscommand: false
      name: Is search completed?
      type: condition
      version: -1
    taskid: d5413bce-fc23-4193-8f07-af3ecd0393ad
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 505
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      limit:
        simple: "5"
      tenant_id:
        simple: ${inputs.tenant_id}
      time_range:
        simple: ${inputs.time_range}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cisco Stealthwatch
      description: Initialize flow search based on parameters. Provide the start time,
        time range, or start time and end time.
      id: cb63f126-e616-466a-814d-90169463f29d
      iscommand: true
      name: cisco-stealthwatch-query-flows-initialize
      script: Cisco Stealthwatch|||cisco-stealthwatch-query-flows-initialize
      type: regular
      version: -1
    taskid: cb63f126-e616-466a-814d-90169463f29d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 180
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      search_id:
        simple: ${CiscoStealthwatch.FlowStatus.id}
      tenant_id:
        simple: ${inputs.tenant_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cisco Stealthwatch
      description: Check the status of the flow search.
      id: e0e12b8e-168d-4c1f-82a3-db7397726f71
      iscommand: true
      name: cisco-stealthwatch-query-flows-status
      script: Cisco Stealthwatch|||cisco-stealthwatch-query-flows-status
      type: regular
      version: -1
    taskid: e0e12b8e-168d-4c1f-82a3-db7397726f71
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 320
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      search_id:
        simple: ${CiscoStealthwatch.FlowStatus.id}
      tenant_id:
        simple: ${inputs.tenant_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cisco Stealthwatch
      description: Flow search results. Use this command after the search job completes.
      id: 0daa60f3-885a-4055-811c-1fb467e9acb3
      iscommand: true
      name: cisco-stealthwatch-query-flows-results
      script: Cisco Stealthwatch|||cisco-stealthwatch-query-flows-results
      type: regular
      version: -1
    taskid: 0daa60f3-885a-4055-811c-1fb467e9acb3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 890
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "6_12_yes": 0.89
    },
    "paper": {
      "dimensions": {
        "height": 1085,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
