contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: ba55103e-b55d-4809-8ee3-67d7986f3781
inputs:
- description: AD Username
  key: username
  playbookInputQuery: null
  required: true
  value: {}
name: Alex Training.- AD Password Reset
outputs:
- contextPath: NEW_PASSWORD
  description: The new password generated for the user.
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 16f5543b-c468-4217-85a1-c5f24875aa07
      iscommand: false
      name: ""
      version: -1
    taskid: 16f5543b-c468-4217-85a1-c5f24875aa07
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      min_digits:
        simple: "1"
      min_lcase:
        simple: "1"
      min_symbols:
        simple: "1"
      min_ucase:
        simple: "1"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Active Directory Query v2 (XSOAR Engineer Training)
      description: "This function generates a password and allows various parameters
        to customize the properties of the password depending on the use case (e.g.
        password complexity requirements).  The default behavior is to generate a
        password of  *random length* including all four character classes (upper,
        lower, digits, symbols) with at least five and at most ten characters per
        class. \n\nThe min_* values all default to 0. This means that if the command
        is executed in this way:\n!GeneratePassword max_lcase=10\nIt is possible that
        a password of length zero could be generated. It is therefore recommended
        to always include a min_* parameter that matches. \n\nThe debug parameter
        will print certain properties of the command into the WarRoom for easy diagnostics."
      id: 4ca08ec0-ea62-401a-80a5-7085816634cb
      iscommand: false
      name: Generate Temp Passowrd
      script: GeneratePassword
      type: regular
      version: -1
    taskid: 4ca08ec0-ea62-401a-80a5-7085816634cb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      password:
        simple: ${NEW_PASSWORD}
      username:
        simple: ${inputs.username}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Active Directory Query v2 (XSOAR Engineer Training)
      description: Sets a new password for an Active Directory user. This command
        requires a secure connection (SSL,TLS).
      id: 4b3afdd6-8c8e-44cf-84a1-966dde3bc231
      iscommand: true
      name: Set User Password
      script: Active Directory Query v2 (XSOAR Engineer Training)|||ad-set-new-password
      type: regular
      version: -1
    taskid: 4b3afdd6-8c8e-44cf-84a1-966dde3bc231
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 350
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      username:
        simple: ${inputs.username}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Active Directory Query v2 (XSOAR Engineer Training)
      description: Expires the password of an Active Directory user.
      id: 5b0f7a50-6f49-45a4-862c-ebc72e85e215
      iscommand: true
      name: Expire User Password
      script: Active Directory Query v2 (XSOAR Engineer Training)|||ad-expire-password
      type: regular
      version: -1
    taskid: 5b0f7a50-6f49-45a4-862c-ebc72e85e215
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 560
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b0e3cddd-4332-4779-80e6-61c68856ed6f
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: b0e3cddd-4332-4779-80e6-61c68856ed6f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 750
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 390,
        "x": 450,
        "y": 50
      }
    }
  }
