contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.0.10
    packID: RiskSense
    packName: RiskSense
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Block IPs and apply the tag to assets that are vulnerable to the specified
  CVE.
id: CVE Exposure - RiskSense
inputs:
- description: Specify Common Vulnerabilities and Exposures (CVE). You can mention
    multiple CVEs using a comma-separated list.
  key: CVES
  playbookInputQuery: null
  required: true
  value: {}
- description: Tags in RiskSense can be applied to assets, web applications, and vulnerabilities.
    Tags are useful in the soft grouping, workflow creation and to identify compliance-related
    assets.
  key: TagName
  playbookInputQuery: null
  required: true
  value: {}
name: CVE Exposure - RiskSense
outputs:
- contextPath: RiskSense.TagAssociation
  description: Tag association details including tag name, association ID, created.
  type: unknown
- contextPath: RiskSense.HostFinding
  description: List of the host finding details.
  type: unknown
- contextPath: RiskSense.Host
  description: List of the host details.
  type: unknown
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: start
      id: 0c2f9026-080c-4894-8d97-98e4d8756703
      iscommand: false
      name: ""
      version: -1
    taskid: 0c2f9026-080c-4894-8d97-98e4d8756703
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 130,
          "y": 40
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: RiskSense
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if RiskSense is enabled. Otherwise returns 'no'.
      id: 5c12e6b5-bebc-4667-845d-eeb7d826155a
      iscommand: false
      name: Is RiskSense enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 5c12e6b5-bebc-4667-845d-eeb7d826155a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 140,
          "y": 370
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      assettype:
        simple: host
      fieldname:
        simple: id
      operator:
        simple: IN
      tagname:
        complex:
          root: inputs.TagName
      value:
        complex:
          accessor: HostFinding.HostID
          root: RiskSense
          transformers:
          - operator: uniq
          - operator: Stringify
          - args:
              separator:
                value:
                  simple: ','
            operator: join
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Apply the new or existing tag to the asset, or creates a new tag
        if the tag does not exist in RiskSense.
      id: e1a7f22d-c964-4537-80f8-c71c9ee58cd1
      iscommand: true
      name: Apply tag to found assets
      script: '|||risksense-apply-tag'
      type: regular
      version: -1
    taskid: e1a7f22d-c964-4537-80f8-c71c9ee58cd1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 490,
          "y": 1080
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Done
      id: 7c77c3b8-f938-4e1d-81d7-9c04db2847fb
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 7c77c3b8-f938-4e1d-81d7-9c04db2847fb
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -220,
          "y": 1510
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      fieldname:
        simple: cves
      operator:
        simple: IN
      size:
        simple: "1000"
      sort_by:
        simple: Risk Rating
      sort_direction:
        simple: Descending
      status:
        simple: Open
      value:
        complex:
          root: inputs.CVES
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: A detailed host finding view with the severity level. Displays
        vulnerability information like CVE, threats associated with current findings,
        and origin of findings.
      id: 16aa966e-1fd7-45c8-8d54-1107fd958cdf
      iscommand: true
      name: Get open findings related to CVEs
      script: '|||risksense-get-host-findings'
      type: regular
      version: -1
    taskid: 16aa966e-1fd7-45c8-8d54-1107fd958cdf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 710
        }
      }
  "12":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: RiskSense.HostFinding.ID
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "6"
      - "14"
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if asset findings found. Otherwise returns 'no'
      id: 4f42421d-9238-4871-8d95-48ef34cc08ae
      iscommand: false
      name: Are asset findings found?
      type: condition
      version: -1
    taskid: 4f42421d-9238-4871-8d95-48ef34cc08ae
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 865
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9f36553b-2b15-4a90-85e0-65c486068d89
      iscommand: false
      name: Get assets findings with the asset and perform actions
      type: title
      version: -1
    taskid: 9f36553b-2b15-4a90-85e0-65c486068d89
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 590
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8023da73-46df-44a8-8355-9876a09da604
      iscommand: false
      name: Blocks IP addresses (requires at least one integration)
      type: title
      version: -1
    taskid: 8023da73-46df-44a8-8355-9876a09da604
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1055
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      fieldname:
        simple: id
      operator:
        simple: IN
      size:
        simple: "1000"
      sort_by:
        simple: RS3
      sort_direction:
        simple: Descending
      value:
        complex:
          accessor: HostFinding.HostID
          root: RiskSense
          transformers:
          - operator: uniq
          - operator: Stringify
          - args:
              separator:
                value:
                  simple: ','
            operator: join
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets details of the supplied host. The host details can be searched
        based on input parameters like fieldname (Host Name, IP Address, Criticality,
        etc), operator (EXACT, IN, LIKE, BETWEEN), page, size, sort by, and sort direction.
      id: ea128f99-f05a-47c6-8893-1c42fa831a2a
      iscommand: true
      name: Get asset information with owner
      script: '|||risksense-get-hosts'
      type: regular
      version: -1
    taskid: ea128f99-f05a-47c6-8893-1c42fa831a2a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1215
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      assettype:
        simple: hostFinding
      fieldname:
        simple: id
      operator:
        simple: IN
      tagname:
        complex:
          root: inputs.TagName
      value:
        complex:
          accessor: HostFinding.ID
          root: RiskSense
          transformers:
          - operator: uniq
          - operator: Stringify
          - args:
              separator:
                value:
                  simple: ','
            operator: join
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Apply the new or existing tag to the asset, or creates a new tag
        if it does not exist in RiskSense.
      id: 4083fb31-386a-4e65-8a14-78b53786244d
      iscommand: true
      name: Apply tag to found asset findings
      script: '|||risksense-apply-tag'
      type: regular
      version: -1
    taskid: 4083fb31-386a-4e65-8a14-78b53786244d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1215
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      AutoCommit:
        simple: "No"
      CustomBlockRule:
        simple: "True"
      IP:
        complex:
          accessor: HostFinding.HostIpAddress
          root: RiskSense
          transformers:
          - operator: uniq
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: b31a916a-9752-45fb-8354-5856a5124be6
      iscommand: false
      name: Block IP - Generic v2
      playbookId: Block IP - Generic v2
      type: playbook
      version: -1
    taskid: b31a916a-9752-45fb-8354-5856a5124be6
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1215
        }
      }
  "18":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.CVES
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.TagName
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if inputs are provided. Otherwise returns 'no'.
      id: 7a49df8d-d2c9-44a4-897a-4ea385ed52f3
      iscommand: false
      name: Are Inputs provided?
      type: condition
      version: -1
    taskid: 7a49df8d-d2c9-44a4-897a-4ea385ed52f3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 130,
          "y": 175
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "12_10_#default#": 0.17,
      "12_15_yes": 0.76,
      "18_1_yes": 0.18,
      "1_10_#default#": 0.8
    },
    "paper": {
      "dimensions": {
        "height": 1535,
        "width": 1510,
        "x": -220,
        "y": 40
      }
    }
  }
