contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.5.0
    itemVersion: 1.0.9
    packID: Symantec_Messaging_Gateway
    packName: Symantec Messaging Gateway
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  This playbook blocks domains using Symantec Messaging Gateway.
  The playbook checks whether the Symantec Messaging Gateway integration is enabled, whether the Domain input has been provided and if so, blocks the domain.
id: Block Domain - Symantec Messaging Gateway
inputs:
- description: The Domain to block.
  key: Domain
  playbookInputQuery: null
  required: false
  value: {}
name: Block Domain - Symantec Messaging Gateway
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1ff15490-2b31-4e36-896d-faddb7a98b9d
      iscommand: false
      name: ""
      version: -1
    taskid: 1ff15490-2b31-4e36-896d-faddb7a98b9d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -70
        }
      }
  "1":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Symantec Messaging Gateway
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: Active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Verify that there is a valid instance of Check Point Firewall enabled.
      id: cc4526d7-39ab-42ac-8569-feb37fa265fe
      iscommand: false
      name: Is Symantec Messaging Gateway enabled?
      type: condition
      version: -1
    taskid: cc4526d7-39ab-42ac-8569-feb37fa265fe
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 280
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      domain:
        complex:
          root: inputs.Domain
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Adds domain to the Local Bad Sender Domains group.
      id: 9d558c50-4945-45c7-81f2-15c7b130c38a
      iscommand: true
      name: Block Domain
      script: '|||smg-block-domain'
      type: regular
      version: -1
    taskid: 9d558c50-4945-45c7-81f2-15c7b130c38a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 480
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f3e2e096-cec3-4658-8bd0-517a7d4521fb
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: f3e2e096-cec3-4658-8bd0-517a7d4521fb
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 670
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Domain
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the necessary inputs were provided
      id: 90796878-1467-44fd-8bf6-55a869bd827d
      iscommand: false
      name: Check if Domain input was provided
      type: condition
      version: -1
    taskid: 90796878-1467-44fd-8bf6-55a869bd827d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 70
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_2_yes": 0.5,
      "4_1_yes": 0.63
    },
    "paper": {
      "dimensions": {
        "height": 805,
        "width": 380,
        "x": 450,
        "y": -70
      }
    }
  }
