contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.0.13
    packID: ExtraHop
    packName: ExtraHop Reveal(x)
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Links the Demisto incident back to the ExtraHop detection that created
  it for ticket tracking purposes.
id: ExtraHop - Ticket Tracking v2
inputs:
- description: Set to true to assign only user that is currently on shift. Requires
    Cortex XSOAR v5.5 or later.
  key: OnCall
  playbookInputQuery: null
  required: false
  value:
    simple: "false"
name: ExtraHop - Ticket Tracking v2
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 71394f2c-bc76-4885-8bab-b55ce0094789
      iscommand: false
      name: ""
      version: -1
    taskid: 71394f2c-bc76-4885-8bab-b55ce0094789
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": -10,
          "y": -460
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      detection_id:
        complex:
          accessor: CustomFields.detectionid
          root: foundIncidents
      incident_close_reason:
        complex:
          accessor: closeReason
          root: foundIncidents
      incident_id:
        complex:
          accessor: id
          root: foundIncidents
      incident_owner:
        complex:
          accessor: owner
          root: foundIncidents
      incident_status:
        complex:
          accessor: status
          root: foundIncidents
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Link the ExtraHop Detection to the corresponding Demisto Investigation.  This
        uses the ExtraHop ticket tracking functionality to properly display ticket
        status within ExtraHop.
      id: be00a185-8d20-4e46-8012-4ae44b3687fc
      iscommand: true
      name: Track the incident status in ExtraHop Reveal(x)
      script: '|||extrahop-track-ticket'
      type: regular
      version: -1
    taskid: be00a185-8d20-4e46-8012-4ae44b3687fc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 170,
          "y": 1110
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f4953d89-2219-4d74-8acf-d819728d0ac9
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: f4953d89-2219-4d74-8acf-d819728d0ac9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -100,
          "y": 1640
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      detectionticketed:
        simple: "true"
      id:
        simple: ${ExtraHop.TicketId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Update the incident to reflect the Detection Ticketed status.
      id: 6f9852cc-7a6e-4d2f-8bef-86fb205e5408
      iscommand: true
      name: Mark the incident as tracked
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 6f9852cc-7a6e-4d2f-8bef-86fb205e5408
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 490,
          "y": 600
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: type:"ExtraHop Detection" and incident.detectionticketed:F and incident.created:>="1
          day ago"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Searches Demisto incidents for any ExtraHop Detections that are
        untracked.
      id: 695438ce-bf6a-43e8-8d73-3b314c1ea1e5
      iscommand: false
      name: Search for any untracked ExtraHop Detections
      script: SearchIncidentsV2
      type: regular
      version: -1
    taskid: 695438ce-bf6a-43e8-8d73-3b314c1ea1e5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 170,
          "y": 770
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      detectionticketed:
        simple: "true"
      id:
        simple: ${ExtraHop.TicketId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Update the incident to reflect the Detection Ticketed status.
      id: 75eb04ec-c770-4120-8d70-56513ce2201b
      iscommand: true
      name: Mark the incident as tracked
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 75eb04ec-c770-4120-8d70-56513ce2201b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 170,
          "y": 1465
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      detection_id:
        simple: ${incident.detectionid}
      incident_close_reason:
        simple: ${incident.closeReason}
      incident_id:
        simple: ${incident.id}
      incident_owner:
        simple: ${incident.owner}
      incident_status:
        simple: ${incident.status}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Link the ExtraHop Detection to the corresponding Demisto Investigation.  This
        uses the ExtraHop ticket tracking functionality to properly display ticket
        status within ExtraHop.
      id: 50b89e52-0733-477b-8929-8b595f704ca4
      iscommand: true
      name: Track the incident status in ExtraHop Reveal(x)
      script: '|||extrahop-track-ticket'
      type: regular
      version: -1
    taskid: 50b89e52-0733-477b-8929-8b595f704ca4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 490,
          "y": 230
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.id
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: incident.detectionid
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the required detection and incident IDs are present.
      id: 40271f8c-840d-4e71-86c5-57a28bc24aea
      iscommand: false
      name: Are the required fields present?
      type: condition
      version: -1
    taskid: 40271f8c-840d-4e71-86c5-57a28bc24aea
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 170,
          "y": 50
        }
      }
  "10":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: foundIncidents.id
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there were any untracked ExtraHop Detections found.
      id: 76071ff8-9c4d-494d-8b73-aa4368199fb5
      iscommand: false
      name: Were there any incidents found?
      type: condition
      version: -1
    taskid: 76071ff8-9c4d-494d-8b73-aa4368199fb5
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 170,
          "y": 930
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ExtraHop.TicketId
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if the ticket tracking was successful.
      id: e553a569-662c-460e-87f0-f69efaf2901a
      iscommand: false
      name: Was the incident successfully tracked?
      type: condition
      version: -1
    taskid: e553a569-662c-460e-87f0-f69efaf2901a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 490,
          "y": 390
        }
      }
  "12":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ExtraHop.TicketId
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if the ticket tracking was successful.
      id: 624c3b07-31d8-45ca-8f6f-332974515fef
      iscommand: false
      name: Was the incident successfully tracked?
      type: condition
      version: -1
    taskid: 624c3b07-31d8-45ca-8f6f-332974515fef
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 170,
          "y": 1275
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      onCall:
        complex:
          root: inputs.OnCall
      roles:
        simple: ExtraHop
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Assign an analyst randomly from the pool of users with the ExtraHop
        role.
      id: 1619242b-d813-4dfb-8801-cd45a61906f3
      iscommand: false
      name: Assign an ExtraHop analyst to the incident
      script: AssignAnalystToIncident
      type: regular
      version: -1
    taskid: 1619242b-d813-4dfb-8801-cd45a61906f3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 170,
          "y": -110
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: brand
              operator: isEqualString
              right:
                value:
                  simple: ExtraHop v2
          - - left:
                iscontext: true
                value:
                  simple: state
              operator: isEqualString
              right:
                value:
                  simple: active
          root: modules
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is an active instance of the ExtraHop Reveal(x)
        integration enabled.
      id: dffb9228-cc49-4adf-88f5-13001f85ba70
      iscommand: false
      name: Is ExtraHop Reveal(x) enabled?
      script: Exists
      type: condition
      version: -1
    taskid: dffb9228-cc49-4adf-88f5-13001f85ba70
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -10,
          "y": -320
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "10_1_yes": 0.42,
      "10_2_#default#": 0.2,
      "11_3_yes": 0.49,
      "11_4_#default#": 0.45,
      "12_2_#default#": 0.31,
      "12_6_yes": 0.47,
      "15_13_yes": 0.55,
      "15_2_#default#": 0.1,
      "9_4_#default#": 0.31,
      "9_7_yes": 0.44
    },
    "paper": {
      "dimensions": {
        "height": 2165,
        "width": 970,
        "x": -100,
        "y": -460
      }
    }
  }
