contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.2.0
    itemVersion: 1.0.1
    packID: SecneurXAnalysis
    packName: SecneurX Analysis
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Detonates a file using the SecneurX Analysis Integration. Returns relevant
  reports to the War Room and file reputations to the context data.
id: Detonate File - SecneurX Analysis
inputs:
- description: File object of the file to detonate. The File is taken from the context.
  key: File
  playbookInputQuery: null
  required: false
  value:
    complex:
      root: File
- description: 'Operating system platform to run the analysis on. Supported values
    are: ["Windows7", "Windows10", "Android", "Ubuntu"].'
  key: Platform
  playbookInputQuery: null
  required: false
  value:
    simple: Windows7
- description: Analysis duration in seconds.
  key: Duration
  playbookInputQuery: null
  required: false
  value:
    simple: "120"
- description: Analysis priority. Possible values are "High" or "Normal".
  key: Priority
  playbookInputQuery: null
  required: false
  value:
    simple: Normal
- description: 'Extension of the submitted file. Supported values are: ["sh", "js",
    "7z", "py", "doc", "rtf", "xls", "ppt", "pps", "ps1", "bat", "eml", "exe", "iso",
    "jar", "txt", "odt", "odp", "ods", "swf", "msg", "msi", "url", "pdf", "rar", "vbs",
    "zip", "cab", "lnk", "xml", "dll", "tar", "hta", "elf", "docx", "docm", "link",
    "xlsx", "xlsm", "xlsb", "pptx", "ppam", "html"].'
  key: Extension
  playbookInputQuery: null
  required: false
  value: {}
- description: Reboot the system during analysis. The value should be "True" or "False".
  key: Reboot
  playbookInputQuery: null
  required: false
  value:
    simple: "False"
- description: Password of the submitted file.
  key: FilePassword
  playbookInputQuery: null
  required: false
  value: {}
- description: 'The resource type to download. Supported values are: ["json", "html"].'
  key: ReportFormat
  playbookInputQuery: null
  required: false
  value:
    simple: json
- description: Duration for executing the pooling (in minutes).
  key: Interval
  playbookInputQuery: null
  required: false
  value:
    simple: "1"
- description: The duration after which to stop pooling and to resume the playbook
    (in minutes).
  key: Timeout
  playbookInputQuery: null
  required: false
  value:
    simple: "15"
name: Detonate File - SecneurX Analysis
outputs:
- contextPath: SecneurXAnalysis.Report.SHA256
  description: SHA256 value of the analyzed sample
  type: string
- contextPath: SecneurXAnalysis.Report.Platform
  description: Platform of the analyzed sample
  type: String
- contextPath: SecneurXAnalysis.Report.Verdict
  description: Summary result of the analyzed sample
  type: string
- contextPath: SecneurXAnalysis.Report.Tags
  description: More details of the analyzed sample
  type: string
- contextPath: SecneurXAnalysis.Report.DnsRequests
  description: List of DNS data observed in the analyzed sample
  type: string
- contextPath: SecneurXAnalysis.Report.HttpRequests
  description: List of HTTP data observed in the analyzed sample
  type: string
- contextPath: SecneurXAnalysis.Report.JA3Digests
  description: List of JA3 data observed in the analyzed sample
  type: string
- contextPath: SecneurXAnalysis.Report.ProcessCreated
  description: Process behaviour data observed in the analyzed sample
  type: string
- contextPath: SecneurXAnalysis.Report.RegistrySet
  description: List of Registry creations observed in the analyzed sample
  type: string
- contextPath: SecneurXAnalysis.Report.RegistryDeleted
  description: List of Registry deletions observed in the analyzed sample
  type: string
- contextPath: SecneurXAnalysis.Report.FileCreated
  description: List of File creations observed in the analyzed sample
  type: string
- contextPath: SecneurXAnalysis.Report.FileDropped
  description: List of File drops observed in the analyzed sample
  type: string
- contextPath: SecneurXAnalysis.Report.FileDeleted
  description: List of File deletions observed in the analyzed sample
  type: string
- contextPath: SecneurXAnalysis.Report.FileModified
  description: List of File changes observed in the analyzed sample
  type: string
- contextPath: SecneurXAnalysis.Report.IOC
  description: List of IOC's observed in the analyzed sample
  type: string
- contextPath: SecneurXAnalysis.Report.Status
  description: Analysis queued sample state
  type: String
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Playbook Start Point
      id: f656b78d-451c-4524-84dd-d44a32a4c567
      iscommand: false
      name: ""
      version: -1
    taskid: f656b78d-451c-4524-84dd-d44a32a4c567
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1410,
          "y": -20
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Secneurx Analysis
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isEqualString
          right:
            value:
              simple: Secneurx Analysis
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if SecneurX Analysis sandbox is configured?
      id: 7c8df86a-c8a9-49b8-8d16-e7c943468a19
      iscommand: false
      name: Is SecneurX Analysis enabled?
      type: condition
      version: -1
    taskid: 7c8df86a-c8a9-49b8-8d16-e7c943468a19
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1410,
          "y": 130
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.File
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a File is provided?
      id: 7a416d29-23b4-48ba-8e38-69f56a2d90d6
      iscommand: false
      name: Is there a File to detonate?
      type: condition
      version: -1
    taskid: 7a416d29-23b4-48ba-8e38-69f56a2d90d6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 320
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      Duration:
        complex:
          root: inputs.Duration
      EntryID:
        complex:
          accessor: EntryID
          root: inputs.File
      Extension:
        complex:
          root: inputs.Extension
      File Password:
        complex:
          root: inputs.FilePassword
      Platform:
        complex:
          root: inputs.Platform
      Priority:
        complex:
          root: inputs.Priority
      Reboot:
        complex:
          root: inputs.Reboot
    separatecontext: false
    skipunavailable: false
    task:
      brand: Secneurx Analysis
      description: Submit the file to SecneurX Analysis.
      id: 571ca6b5-34f7-4401-8ea4-8af14cc01eea
      iscommand: true
      name: SecneurX Analysis File Upload
      script: Secneurx Analysis|||snx-analysis-submit-file
      type: regular
      version: -1
    taskid: 571ca6b5-34f7-4401-8ea4-8af14cc01eea
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 570
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: SecneurXAnalysis.SubmitFile.task_uuid
                    operator: isExists
                root: SecneurXAnalysis.SubmitFile
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Receive the Task UUID (unique ID) returned by the upload command.
      id: 93861b6d-9961-4b50-8234-0dc06bc8b817
      iscommand: false
      name: Filter UUIDs?
      type: condition
      version: -1
    taskid: 93861b6d-9961-4b50-8234-0dc06bc8b817
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 770
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Playbook End Point
      id: 73768251-504d-4b65-847d-afcdec87a9ce
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 73768251-504d-4b65-847d-afcdec87a9ce
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1470,
          "y": 1370
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      report_format:
        complex:
          root: inputs.ReportFormat
      task_uuid:
        complex:
          accessor: task_uuid
          root: SecneurXAnalysis.SubmitFile
    separatecontext: false
    skipunavailable: false
    task:
      brand: Secneurx Analysis
      description: Get the detailed report of the analyzed sample.
      id: bd527b7c-56b9-4242-8e47-e4b05cd9ec95
      iscommand: true
      name: SecneurX Analysis Get Report
      script: Secneurx Analysis|||snx-analysis-get-report
      type: regular
      version: -1
    taskid: bd527b7c-56b9-4242-8e47-e4b05cd9ec95
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 1185
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        complex:
          accessor: task_uuid
          root: SecneurXAnalysis.SubmitFile
      Interval:
        complex:
          root: inputs.Interval
      PollingCommandArgName:
        simple: task_uuid
      PollingCommandName:
        simple: snx-analysis-get-verdict
      Timeout:
        complex:
          root: inputs.Timeout
      dt:
        simple: SecneurXAnalysis.Verdict(val.status !== 'Completed' && val.status
          !== 'Failed').task_uuid
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 795b4d81-131f-4895-85f3-007da164c572
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 795b4d81-131f-4895-85f3-007da164c572
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 980
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_2_yes": 0.51,
      "1_6_#default#": 0.1,
      "2_3_yes": 0.44,
      "2_6_#default#": 0.27,
      "4_13_yes": 0.59,
      "4_6_#default#": 0.39
    },
    "paper": {
      "dimensions": {
        "height": 1455,
        "width": 740,
        "x": 1110,
        "y": -20
      }
    }
  }
