contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.1.0
    itemVersion: 1.0.1
    packID: Change_Management
    packName: Change Management
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  If you are using PAN-OS/Panorama firewall and Jira or ServiceNow as a ticketing system this playbook is a perfect match for your change management for Firewall process.
  This playbook can be triggered by 2 different options - a fetch from ServiceNow or Jira - and will help you manage and automate your change management process.
id: Change Management
inputs:
- description: Provide a summery for your firewall change request.
  key: TicketSummary
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: details
      root: incident
- description: The email of the security team that approves the firewall requests.
  key: SecurityTeamEmail
  playbookInputQuery: null
  required: false
  value: {}
- description: 'Log type to query. Can be: traffic, threat, wildfire, url or data-filtering.'
  key: log_type
  playbookInputQuery: null
  required: false
  value:
    simple: traffic
- description: The query string by which to match criteria for the logs. This is similar
    to the query provided in the web interface under the Monitor tab when viewing
    the logs.
  key: query
  playbookInputQuery: null
  required: false
  value: {}
- description: By providing the value "Yes" to this input, the "Panorama Query Logs"
    playbook will be activated.
  key: Query_logs
  playbookInputQuery: null
  required: false
  value:
    simple: "Yes"
- description: The source address for the change request.
  key: addr-src
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: sourceips
      root: incident
- description: The destination address for the change request.
  key: addr-dst
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: destinationips
      root: incident
- description: The destination ports for the change request.
  key: port-dst
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: dstports
      root: incident
- description: The relevant firewall source zone for the change request.
  key: zone-src
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: sourcenetworks
      root: incident
- description: The relevant firewall destination zone for the change request.
  key: zone-dst
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: destinationnetworks
      root: incident
- description: 'The action for the change request (such as: allow, drop, deny)'
  key: Action
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: policyactions
      root: incident
- description: The relevant IP protocol for the change request.
  key: Protocol
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: protocol
      root: incident
- description: Log forwarding profile.
  key: Log_forwarding
  playbookInputQuery: null
  required: false
  value: {}
- description: A profile setting group.
  key: Profile_setting
  playbookInputQuery: null
  required: false
  value: {}
- description: A comma-separated list of service object names for the rule.
  key: Service
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: protocolnames
      root: incident
- description: A comma-separated list of application object names for the rule to
    create.
  key: Application
  playbookInputQuery: null
  required: false
  value: {}
- description: Target number of the firewall. Use only for a Panorama instance.
  key: Target
  playbookInputQuery: null
  required: false
  value: {}
- description: Target vsys of the firewall. Use only for a Panorama instance.
  key: Vsys
  playbookInputQuery: null
  required: false
  value: {}
- description: Name of the rule to create.
  key: Rulename
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    Pre rule or Post rule (Panorama instances).
    Possible options:
    - post-rulebase
    - pre-rulebase
  key: Rule_position
  playbookInputQuery: null
  required: false
  value: {}
- description: Set the description of the ticket.
  key: Description
  playbookInputQuery: null
  required: false
  value: {}
- description: 'The time the log was generated from the timestamp and prior to it.
    For example: "2019/08/11 01:10:44".'
  key: Time_generated
  playbookInputQuery: null
  required: false
  value: {}
- description: 'By providing YES to this input, the requested firewall rule will be
    tested in your test environment. '
  key: TestConfigurations
  playbookInputQuery: null
  required: false
  value: {}
- description: The instance name of the firewall in the DEV environment for testing
    the new rule.
  key: TestInstance
  playbookInputQuery: null
  required: false
  value: {}
- description: The closing status in Jira is changing in the project templates. Please
    provide the relevant closing status if the issue was approved.
  key: Closing_status_approved
  playbookInputQuery: null
  required: false
  value: {}
- description: The closing status in Jira is changing in the  project templates. Please
    provide the relevant closing status if the issue was rejected.
  key: Closing_status_rejected
  playbookInputQuery: null
  required: false
  value: {}
- description: "Maximum number of API requests that the \nPanoramaSecurityPolicyMatchWrapper
    script will send.\nThe default is 500."
  key: Limit
  playbookInputQuery: null
  required: false
  value: {}
name: Change Management
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d4e1ffe5-c829-4ac6-84eb-c326f108f5b6
      iscommand: false
      name: ""
      version: -1
    taskid: d4e1ffe5-c829-4ac6-84eb-c326f108f5b6
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 60
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      Action:
        complex:
          root: inputs.Action
      Application:
        complex:
          root: inputs.Application
      Description:
        complex:
          root: inputs.Description
      Limit:
        complex:
          root: inputs.Limit
      Log_forwarding:
        complex:
          root: inputs.Log_forwarding
      Profile_setting:
        complex:
          root: inputs.Profile_setting
      Protocol:
        complex:
          root: inputs.Protocol
      Rule_position:
        complex:
          root: inputs.Rule_position
      Rulename:
        complex:
          root: inputs.Rulename
      SecurityTeamEmail:
        complex:
          root: inputs.SecurityTeamEmail
      Service:
        complex:
          root: inputs.Service
      Target:
        complex:
          root: inputs.Target
      TestConfigurations:
        complex:
          root: inputs.TestConfigurations
      TestInstance:
        complex:
          root: inputs.TestInstance
      TicketSummary:
        complex:
          root: inputs.TicketSummary
      Time-generated:
        complex:
          root: inputs.Time_generated
      Vsys:
        complex:
          root: inputs.Vsys
      addr-dst:
        complex:
          root: inputs.addr-dst
      addr-src:
        complex:
          root: inputs.addr-src
      log_type:
        complex:
          root: inputs.log_type
      port-dst:
        complex:
          root: inputs.port-dst
      query:
        complex:
          root: inputs.query
      zone-dst:
        complex:
          root: inputs.zone-dst
      zone-src:
        complex:
          root: inputs.zone-src
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: "If you are using PAN-OS/Panorama firewall and ServiceNow as a
        ticketing system, this playbook is a perfect match for your change management
        for firewall process.\nThis playbook is triggered by a fetch from ServiceNow
        and will help you manage and automate your change management process.     "
      id: 8be6bb83-2565-455c-8b84-0b36de101cc7
      iscommand: false
      name: ServiceNow Change Management
      playbookId: ServiceNow Change Management
      type: playbook
      version: -1
    taskid: 8be6bb83-2565-455c-8b84-0b36de101cc7
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.sourceBrand
          operator: isEqualString
          right:
            value:
              simple: jira-v2
      label: Jira
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.sourceBrand
          operator: isEqualString
          right:
            value:
              simple: ServiceNow v2
      label: ServicenNow
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      Jira:
      - "5"
      ServicenNow:
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d8954865-57c4-472f-8157-2c9ec31fd59f
      iscommand: false
      name: What was the incident trigger?
      type: condition
      version: -1
    taskid: d8954865-57c4-472f-8157-2c9ec31fd59f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e2959013-70b7-4e83-847d-21a2b6108b46
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: e2959013-70b7-4e83-847d-21a2b6108b46
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      Action:
        complex:
          root: inputs.Action
      Application:
        complex:
          root: inputs.Application
      Closing_status_approved:
        complex:
          root: inputs.Closing_status_approved
      Closing_status_rejected:
        complex:
          root: inputs.Closing_status_rejected
      Description:
        complex:
          root: inputs.Description
      Limit:
        complex:
          root: inputs.Limit
      Log_forwarding:
        complex:
          root: inputs.Log_forwarding
      Profile_setting:
        complex:
          root: inputs.Profile_setting
      Protocol:
        complex:
          root: inputs.Protocol
      Rule_position:
        complex:
          root: inputs.Rule_position
      Rulename:
        complex:
          root: inputs.Rulename
      SecurityTeamEmail:
        complex:
          root: inputs.SecurityTeamEmail
      Service:
        complex:
          root: inputs.Service
      Target:
        complex:
          root: inputs.Target
      TestConfigurations:
        complex:
          root: inputs.TestConfigurations
      TestInstance:
        complex:
          root: inputs.TestInstance
      TicketSummary:
        complex:
          root: inputs.TicketSummary
      Time-generated:
        complex:
          root: inputs.Time_generated
      Vsys:
        complex:
          root: inputs.Vsys
      addr-dst:
        complex:
          root: inputs.addr-dst
      addr-src:
        complex:
          root: inputs.addr-src
      log_type:
        complex:
          root: inputs.log_type
      port-dst:
        complex:
          root: inputs.port-dst
      query:
        complex:
          root: inputs.query
      zone-dst:
        complex:
          root: inputs.zone-dst
      zone-src:
        complex:
          root: inputs.zone-src
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: |-
        If you are using PAN-OS/Panorama firewall and Jira as a ticketing system, this playbook will be a perfect match for your change management for firewall process.
        This playbook is triggered by a fetch from Jira and will help you manage and automate you change management process.
      id: dcbca05c-4279-4a7b-894d-d89707e77035
      iscommand: false
      name: Jira Change Management
      playbookId: Jira Change Management
      type: playbook
      version: -1
    taskid: dcbca05c-4279-4a7b-894d-d89707e77035
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 475,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "3_2_ServicenNow": 0.46
    },
    "paper": {
      "dimensions": {
        "height": 550,
        "width": 805,
        "x": 50,
        "y": 60
      }
    }
  }
