contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: 'This playbook demos the BYOI OpenWeatherMap integration, as part of
  the XSOAR Training Pack. '
id: c4b6bcdc-14f5-49af-865d-6fdfb291d741
inputs: []
name: XSOAR Engineer Training - BYOI Take a Half Day
outputs: []
sourceplaybookid: 9211a701-c9e4-4b57-8043-1c589b6f857b
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 70be86b5-d024-49b2-8058-66a5018af003
      iscommand: false
      name: ""
      version: -1
    taskid: 70be86b5-d024-49b2-8058-66a5018af003
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      city:
        complex:
          accessor: "0"
          root: Half Day.Answers
    separatecontext: false
    skipunavailable: false
    task:
      brand: OpenWeatherMap
      description: Retrieves the weather by provided city (where you wish you were)
      id: 1c066284-e64c-47ee-89e2-f65f8404c850
      iscommand: true
      name: Get the current Weather for ${Half Day.Answers.0}
      script: OpenWeatherMap|||openweather-by-city
      type: regular
      version: -1
    taskid: 1c066284-e64c-47ee-89e2-f65f8404c850
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: OpenWeather.CurrentWeather.High
          operator: lessThan
          right:
            value:
              simple: "75"
      - - left:
            iscontext: true
            value:
              simple: OpenWeather.CurrentWeather.Low
          operator: greaterThanOrEqual
          right:
            value:
              simple: "20"
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: a77cec6d-b2d1-465a-85fc-cdbe4fab0795
      iscommand: false
      name: Is Today a Good Day to Half Day?
      type: condition
      version: -1
    taskid: a77cec6d-b2d1-465a-85fc-cdbe4fab0795
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "3":
    continueonerrortype: ""
    evidencedata:
      customfields: {}
      description:
        simple: Half Day!!
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: true
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      value:
        simple: '# HALF DAY!'
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV2
      description: Prints text to war room (Markdown supported)
      id: f0c0387c-9db1-4f5e-88ae-b405d9dfe5c4
      iscommand: false
      name: Notify Ori - Half day is on the menu!
      script: Print
      type: regular
      version: -1
    taskid: f0c0387c-9db1-4f5e-88ae-b405d9dfe5c4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 1339ae0f-022d-4b9c-83a2-172402f64206
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 1339ae0f-022d-4b9c-83a2-172402f64206
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1420
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "7"
      "yes":
      - "6"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      brandname:
        simple: OpenWeatherMap
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 185ff839-5f16-4153-80ad-b7f12a0b6d80
      iscommand: false
      name: Is the Open Weather integration available?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 185ff839-5f16-4153-80ad-b7f12a0b6d80
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "6":
    continueonerrortype: ""
    form:
      description: To half day or not to half day, is it even a question?
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: City
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: City
        type: shortText
      sender: ""
      title: Half Day
      totalanswers: 0
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Please enter the city you want to check the weather for.
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: false
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    reputationcalc: 1
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4eee72ad-66f7-4c3b-8d25-52321824efe2
      iscommand: false
      name: What city do you want to check the weather for?
      type: collection
      version: -1
    taskid: 4eee72ad-66f7-4c3b-8d25-52321824efe2
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        You need to configure an instance of the OpenWeatherMap integration to run this playbook.

        Configure the integration, and complete this task to continue.
      id: 7736c93a-4763-4932-8e5d-15c369c4d00e
      iscommand: false
      name: Configure the OpenWeatherMap Integration
      type: regular
      version: -1
    taskid: 7736c93a-4763-4932-8e5d-15c369c4d00e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 20,
          "y": 550
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: e0353184-6dc5-4f83-8fe9-9adfe5c8dd2b
      iscommand: false
      name: Delete Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: e0353184-6dc5-4f83-8fe9-9adfe5c8dd2b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: true
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      value:
        simple: 'Today is not a good day to half day.  But do what you need to do. '
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV2
      description: Prints text to war room (Markdown supported)
      id: 8a12aa33-c450-43d0-8d19-5ac656e00d2f
      iscommand: false
      name: 'Weather sub-optimal, not the best day for a half day. '
      script: Print
      type: regular
      version: -1
    taskid: 8a12aa33-c450-43d0-8d19-5ac656e00d2f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1435,
        "width": 840,
        "x": 20,
        "y": 50
      }
    }
  }
