contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: "This is a sub-playbook that simulates an AD Password Reset process,
  which can be used as a sub-playbook across a number of different playbooks simply
  by adding it in, and passing the proper inputs in. \n\nThis sub-playbook will output
  the new password, so it can be provided to the User, or maybe the users manager. "
id: d73a17fd-d200-4c6a-8e5f-396f88534703
inputs:
- description: The samAccountName of the user to reset the password for.
  key: username
  playbookInputQuery: null
  required: true
  value: {}
name: XSOAR Engineer Training - AD Password Reset  (Sub-Playbook)
outputs:
- contextPath: NEW_PASSWORD
  description: The new password generated for the user.
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 243eaea4-5105-482e-8efb-6b2f52cf1da1
      iscommand: false
      name: ""
      version: -1
    taskid: 243eaea4-5105-482e-8efb-6b2f52cf1da1
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      username:
        complex:
          root: inputs.username
    separatecontext: false
    skipunavailable: false
    task:
      brand: Active Directory Query v2 (XSOAR Engineer Training)
      description: Retrieves detailed information about a user account. The user can
        be specified by name, email address, or as an Active Directory Distinguished
        Name (DN). If no filter is specified, all users are returned.
      id: 0c8b1c09-b4dd-47f5-8006-4db25cd92829
      iscommand: true
      name: 'Reset User Password '
      script: Active Directory Query v2 (XSOAR Engineer Training)|||ad-get-user
      type: regular
      version: -1
    taskid: 0c8b1c09-b4dd-47f5-8006-4db25cd92829
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "This function generates a password and allows various parameters
        to customize the properties of the password depending on the use case (e.g.
        password complexity requirements).  The default behavior is to generate a
        password of  *random length* including all four character classes (upper,
        lower, digits, symbols) with at least five and at most ten characters per
        class. \n\nThe min_* values all default to 0. This means that if the command
        is executed in this way:\n!GeneratePassword max_lcase=10\nIt is possible that
        a password of length zero could be generated. It is therefore recommended
        to always include a min_* parameter that matches. \n\nThe debug parameter
        will print certain properties of the command into the WarRoom for easy diagnostics."
      id: 5fbd4de9-6571-476f-86d9-29b2a3c9d031
      iscommand: false
      name: Generate Password
      script: GeneratePassword
      type: regular
      version: -1
    taskid: 5fbd4de9-6571-476f-86d9-29b2a3c9d031
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 74267bab-93e9-4801-83d3-4a38e38f3e9a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 74267bab-93e9-4801-83d3-4a38e38f3e9a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      username:
        complex:
          root: inputs.username
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Expires the password of an Active Directory user.
      id: 6873d949-6b79-430f-8f8b-7b81194b398b
      iscommand: true
      name: Expire Password to force change
      script: '|||ad-expire-password'
      type: regular
      version: -1
    taskid: 6873d949-6b79-430f-8f8b-7b81194b398b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
