contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.1.16
    packID: Kenna
    packName: Kenna
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook accepts an asset, then searches for vulnerabilities on
  that asset using the Kenna integration. If a vulnerability exists, it looks for
  relevant patches, lets the analyst deploy them and then generates an investigation
  summary report.
id: Kenna - Search and Handle Asset Vulnerabilities
inputs:
- description: Deploy vulnerability patches automatically? Specify Yes/No
  key: AutoPatch
  playbookInputQuery: null
  required: false
  value:
    simple: "Yes"
- description: Hostname to search.
  key: hostname
  playbookInputQuery: null
  required: false
  value: {}
- description: Kenna host ID to search.
  key: host_id
  playbookInputQuery: null
  required: false
  value: {}
name: Kenna - Search and Handle Asset Vulnerabilities
outputs:
- contextPath: Report.Name
  description: Report file name
  type: string
- contextPath: Report.FileID
  description: File ID of the report.
  type: string
- contextPath: Kenna.Vulnerabilities.ID
  description: The vulnerability ID.
- contextPath: Kenna.VulnerabilitiesOfAsset.ID
  description: The ID of the vulnerability associated with the the asset.
- contextPath: Kenna.Fixes.ID
  description: The fix ID.
- contextPath: Kenna.Fixes.Assets.ID
  description: The asset ID related to the current fix.
- contextPath: Kenna.Fixes.Vulnerabilities.ID
  description: The vulnerability ID related to the current fix.
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c9901727-39fe-43b9-8d68-a6957da9e30d
      iscommand: false
      name: ""
      version: -1
    taskid: c9901727-39fe-43b9-8d68-a6957da9e30d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": -520
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f4980703-8d81-44c7-83a4-60d8271e08c6
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: f4980703-8d81-44c7-83a4-60d8271e08c6
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1935
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 56527b1b-e40b-4704-8694-a214d821c624
      iscommand: false
      name: CVE enrichment
      type: title
      version: -1
    taskid: 56527b1b-e40b-4704-8694-a214d821c624
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 650,
          "y": 365
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Fixes.ID
                root: Kenna
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6ea0dd13-c5d2-4734-8703-b05c9972f7d1
      iscommand: false
      name: Are there available fixes?
      type: condition
      version: -1
    taskid: 6ea0dd13-c5d2-4734-8703-b05c9972f7d1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 920,
          "y": 1230
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c6207ea1-0976-41d3-8636-17088f23b054
      iscommand: false
      name: Manually deploy patch
      type: regular
      version: -1
    taskid: c6207ea1-0976-41d3-8636-17088f23b054
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1220,
          "y": 1400
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        A script that generates an investigation summary report. It can
        be used in a post-processing flow as well.
      id: 692f4ab3-8daa-4c7c-86d1-1e610334de44
      iscommand: false
      name: Generate investigation summary report
      script: GenerateInvestigationSummaryReport
      type: regular
      version: -1
    taskid: 692f4ab3-8daa-4c7c-86d1-1e610334de44
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 920,
          "y": 1760
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      id:
        complex:
          accessor: VulnerabilitiesOfAsset.ID
          root: Kenna
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Searches for vulnerabilities in Kenna.
      id: 6e60fb9f-34ba-4dc8-8f65-6ca730416a75
      iscommand: true
      name: Kenna - search vulnerability
      script: '|||kenna-search-vulnerabilities'
      type: regular
      version: -1
    taskid: 6e60fb9f-34ba-4dc8-8f65-6ca730416a75
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 650,
          "y": 520
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      id:
        complex:
          accessor: Assets.ID
          root: Kenna
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets vulnerabilities of the specified asset.
      id: fb35ed00-0191-4630-8a07-9a41dc0f837d
      iscommand: true
      name: Kenna - get asset vulnerabilities
      script: '|||kenna-get-asset-vulnerabilities'
      type: regular
      version: -1
    taskid: fb35ed00-0191-4630-8a07-9a41dc0f837d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 650,
          "y": 170
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      hostname:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.hostname
              operator: isNotEmpty
          root: inputs.hostname
      id:
        complex:
          root: inputs.host_id
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Searches for assets.
      id: 9bfa446c-4fff-4a9b-82ac-3aa4b5e7f085
      iscommand: true
      name: Kenna - search assets
      script: '|||kenna-search-assets'
      type: regular
      version: -1
    taskid: 9bfa446c-4fff-4a9b-82ac-3aa4b5e7f085
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 650,
          "y": -30
        }
      }
  "20":
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      id:
        complex:
          accessor: Vulnerabilities.ID
          root: Kenna
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Filters fixes by a given set of vulnerability and asset parameters
        and returns the filtered fixes.
      id: edefc5de-0585-4b2e-837c-ef0963d91ed6
      iscommand: true
      name: Kenna - search fixes
      script: '|||kenna-search-fixes'
      type: regular
      version: -1
    taskid: edefc5de-0585-4b2e-837c-ef0963d91ed6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 920,
          "y": 1040
        }
      }
  "21":
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      id:
        complex:
          accessor: Assets.ID
          root: Kenna
      notes:
        simple: Patched for vulnerability ${Kenna.Fixes.Vulnerabilities.ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Add a comment for the asset describing the patch.
      id: 6762ce1a-c1f2-4a01-8483-2bdab72945e3
      iscommand: true
      name: Kenna - add note for asset
      script: '|||kenna-update-asset'
      type: regular
      version: -1
    taskid: 6762ce1a-c1f2-4a01-8483-2bdab72945e3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1220,
          "y": 1590
        }
      }
  "22":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Vulnerabilities.ID
                root: Kenna
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "20"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cfba542c-fbd4-45fd-8cf0-6653c237a697
      iscommand: false
      name: Were any vulnerabilities found?
      type: condition
      version: -1
    taskid: cfba542c-fbd4-45fd-8cf0-6653c237a697
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 650,
          "y": 870
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 75dc8cb1-8b02-4d80-8ef4-e71dba6a4ecd
      iscommand: false
      name: Remediation
      type: title
      version: -1
    taskid: 75dc8cb1-8b02-4d80-8ef4-e71dba6a4ecd
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 650,
          "y": 700
        }
      }
  "24":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.hostname
          operator: isNotEmpty
        - left:
            iscontext: true
            value:
              complex:
                root: inputs.host_id
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: edb2be78-4470-4f0f-82fa-3d0aec9dc695
      iscommand: false
      name: Is there a host to search?
      type: condition
      version: -1
    taskid: edb2be78-4470-4f0f-82fa-3d0aec9dc695
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 360,
          "y": -200
        }
      }
  "25":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Kennav2
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 96f5131e-4cae-4ed3-8022-43e4093d6b1e
      iscommand: false
      name: Is Kenna v2 integration enabled?
      type: condition
      version: -1
    taskid: 96f5131e-4cae-4ed3-8022-43e4093d6b1e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": -370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "11_13_yes": 0.51,
      "11_14_#default#": 0.39,
      "22_20_yes": 0.59,
      "22_9_#default#": 0.28,
      "24_9_#default#": 0.11,
      "25_9_#default#": 0.11
    },
    "paper": {
      "dimensions": {
        "height": 2520,
        "width": 1550,
        "x": 50,
        "y": -520
      }
    }
  }
