contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.0.8
    packID: Polygon
    packName: Polygon
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Detonate URL using Group-IB THF Polygon integration.
id: Detonate URL - Group-IB TDS Polygon
inputs:
- description: Report requests frequency (minutes)
  key: Interval
  playbookInputQuery: null
  required: true
  value:
    simple: "1"
- description: Report waiting timeout (minutes)
  key: Timeout
  playbookInputQuery: null
  required: true
  value:
    simple: "60"
- description: URL to detonate
  key: url
  playbookInputQuery: null
  required: false
  value:
    simple: ${URL.Data}
name: Detonate URL - Group-IB TDS Polygon
outputs:
- contextPath: File.Name
  description: The full file name (including file extension).
  type: string
- contextPath: File.MD5
  description: The MD5 hash of the file
  type: string
- contextPath: File.SHA1
  description: The SHA1 hash of the file
  type: string
- contextPath: File.SHA256
  description: The SHA256 hash of the file
  type: string
- contextPath: File.Type
  description: File type
  type: string
- contextPath: File.Malicious.Vendor
  description: The vendor that reported the file as malicious
  type: string
- contextPath: File.Malicious.Description
  description: A description explaining why the file was determined to be malicious
  type: string
- contextPath: DBotScore.Indicator
  description: The indicator that was tested
  type: string
- contextPath: DBotScore.Type
  description: The indicator type
  type: string
- contextPath: DBotScore.Vendor
  description: The vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: IP.Address
  description: IP address
  type: string
- contextPath: Domain.Name
  description: The Domain name
  type: string
- contextPath: Domain.DNS
  description: A list of IP objects resolved by DNS.
  type: string
- contextPath: URL.Data
  description: The URL
  type: string
- contextPath: RegistryKey.Path
  description: The path to the registry key
  type: string
- contextPath: RegistryKey.Value
  description: The value at the given RegistryKey.
  type: string
- contextPath: Process.Name
  description: Process name
  type: string
- contextPath: Process.PID
  description: Process PID
  type: number
- contextPath: Process.CommandLine
  description: Process Command Line
  type: string
- contextPath: Process.Path
  description: Process path
  type: string
- contextPath: Process.StartTime
  description: Process start time
  type: date
- contextPath: Process.EndTime
  description: Process end time
  type: date
- contextPath: Polygon.Analysis.ID
  description: Analysis ID in THF
  type: number
- contextPath: Polygon.Analysis.Name
  description: File Name
  type: string
- contextPath: Polygon.Analysis.Size
  description: File Size
  type: number
- contextPath: Polygon.Analysis.Started
  description: Analysis start timestamp
  type: date
- contextPath: Polygon.Analysis.Analyzed
  description: Analysis finish timestamp
  type: date
- contextPath: Polygon.Analysis.MD5
  description: Analyzed file MD5 hash
  type: string
- contextPath: Polygon.Analysis.SHA1
  description: Analyzed file SHA1 hash
  type: string
- contextPath: Polygon.Analysis.SHA256
  description: Analyzed file SHA256
  type: string
- contextPath: Polygon.Analysis.Result
  description: Analysis verdict
  type: string
- contextPath: Polygon.Analysis.Status
  description: The analysis status
  type: string
- contextPath: Polygon.Analysis.Verdict
  description: Analysis verdict
  type: boolean
- contextPath: Polygon.Analysis.Probability
  description: Verdict probability
  type: string
- contextPath: Polygon.Analysis.Families
  description: Malware families
  type: string
- contextPath: Polygon.Analysis.Score
  description: Polygon score
  type: number
- contextPath: Polygon.Analysis.Internet-connection
  description: Internet availability
  type: string
- contextPath: Polygon.Analysis.Type
  description: File type
  type: string
- contextPath: Polygon.Analysis.DumpExists
  description: Network activity dump exists
  type: boolean
- contextPath: Polygon.Analysis.File
  description: The information about files in analysis
  type: unknown
- contextPath: Polygon.Analysis.URL
  description: The information about URL indicators
- contextPath: Polygon.Analysis.IP
  description: The information about IP indicators
- contextPath: Polygon.Analysis.Domain
  description: The information about Domain indicators
- contextPath: Polygon.Analysis.RegistryKey
  description: The information about registry keys which were modified during the
    analysis
- contextPath: Polygon.Analysis.Process
  description: The information about processes started during the analysis
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9501b3b5-5523-40bd-8af6-ae6a9d6ac607
      iscommand: false
      name: ""
      version: -1
    taskid: 9501b3b5-5523-40bd-8af6-ae6a9d6ac607
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 540,
          "y": -10
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3515a2f8-6b03-4061-8125-756cc50294fd
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 3515a2f8-6b03-4061-8125-756cc50294fd
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 540,
          "y": 1630
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        complex:
          accessor: Analysis.ID
          root: Polygon
          transformers:
          - operator: LastArrayElement
      Interval:
        simple: ${inputs.Interval}
      PollingCommandArgName:
        simple: tds_analysis_id
      PollingCommandName:
        simple: polygon-analysis-info
      Timeout:
        simple: ${inputs.Timeout}
      dt:
        simple: Polygon.Analysis(val.Status !== 'Finished').ID
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 70256af8-c846-4973-86a8-9c3361ee58b3
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 70256af8-c846-4973-86a8-9c3361ee58b3
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 840,
          "y": 530
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      tds_analysis_id:
        complex:
          accessor: Analysis.ID
          root: Polygon
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    skipunavailable: false
    task:
      brand: Group-IB TDS Polygon
      description: Export an archive with THF Polygon report to War Room
      id: 6948ec34-2400-4760-8be6-a298743c12d2
      iscommand: true
      name: polygon-export-report
      script: Group-IB TDS Polygon|||polygon-export-report
      type: regular
      version: -1
    taskid: 6948ec34-2400-4760-8be6-a298743c12d2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 840,
          "y": 870
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      tds_analysis_id:
        complex:
          accessor: Analysis.ID
          root: Polygon
          transformers:
          - operator: LastArrayElement
      tds_file_id:
        complex:
          accessor: Analysis.ID
          root: Polygon
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    skipunavailable: false
    task:
      brand: Group-IB TDS Polygon
      description: Get THF Polygon analysis information
      id: 4a79b7e8-4212-4b47-8078-bfb2dde6e1b4
      iscommand: true
      name: polygon-analysis-info
      script: Group-IB TDS Polygon|||polygon-analysis-info
      type: regular
      version: -1
    taskid: 4a79b7e8-4212-4b47-8078-bfb2dde6e1b4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 840,
          "y": 700
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      tds_analysis_id:
        complex:
          accessor: Analysis.ID
          root: Polygon
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    skipunavailable: false
    task:
      brand: Group-IB TDS Polygon
      description: Network activity dump export
      id: 987e1a83-e302-4ddc-8aba-e27e41baebe3
      iscommand: true
      name: polygon-export-pcap
      script: Group-IB TDS Polygon|||polygon-export-pcap
      type: regular
      version: -1
    taskid: 987e1a83-e302-4ddc-8aba-e27e41baebe3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 840,
          "y": 1440
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      tds_analysis_id:
        complex:
          accessor: Analysis.ID
          root: Polygon
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    skipunavailable: false
    task:
      brand: Group-IB TDS Polygon
      description: Screen activity video export
      id: 4df106af-8c5f-4bc6-84e8-7c9617694f27
      iscommand: true
      name: polygon-export-video
      script: Group-IB TDS Polygon|||polygon-export-video
      type: regular
      version: -1
    taskid: 4df106af-8c5f-4bc6-84e8-7c9617694f27
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 840,
          "y": 1285
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      url:
        simple: ${inputs.url}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Group-IB TDS Polygon
      description: Upload URL for analysis
      id: 51f1cc88-20ec-4c3f-81f2-2825221bcc6e
      iscommand: true
      name: polygon-upload-url
      script: Group-IB TDS Polygon|||polygon-upload-url
      type: regular
      version: -1
    taskid: 51f1cc88-20ec-4c3f-81f2-2825221bcc6e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 840,
          "y": 350
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          accessor: brand
          filters:
          - - left:
                iscontext: true
                value:
                  simple: modules.brand
              operator: isEqualString
              right:
                value:
                  simple: Group-IB TDS Polygon
          - - left:
                iscontext: true
                value:
                  simple: modules.state
              operator: isEqualString
              right:
                value:
                  simple: active
          root: modules
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 466aa1ae-b36c-4232-86f0-89cf7d19a2d3
      iscommand: false
      name: Is THF Polygon integration enabled?
      script: Exists
      type: condition
      version: -1
    taskid: 466aa1ae-b36c-4232-86f0-89cf7d19a2d3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 540,
          "y": 140
        }
      }
  "20":
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          accessor: Analysis.Result
          root: Polygon
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value is true. Will return 'no' otherwise
      id: 1bbc3dd0-04f3-43e6-833e-93f803184027
      iscommand: false
      name: Is URL malicious?
      script: IsTrue
      type: condition
      version: -1
    taskid: 1bbc3dd0-04f3-43e6-833e-93f803184027
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 840,
          "y": 1060
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1705,
        "width": 680,
        "x": 540,
        "y": -10
      }
    }
  }
