contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.0.10
    packID: RiskSense
    packName: RiskSense
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: The ransomware exposure playbook reveals an organization's exposure to
  the specific vulnerabilities that are being exploited to launch ransomware attacks.
id: Ransomware Exposure - RiskSense
inputs: []
name: Ransomware Exposure - RiskSense
outputs:
- contextPath: RiskSense.RansomwareCves
  description: List of ransomware CVEs, including threats and vulnerabilities.
  type: unknown
- contextPath: RiskSense.RansomwareTrendingCves
  description: List of trending (Last 7 days) ransomware CVEs, including threats and
    vulnerabilities.
  type: unknown
- contextPath: RiskSense.HostFinding
  description: List of host finding details.
  type: unknown
- contextPath: RiskSense.Host
  description: List of host details.
  type: unknown
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 576ef95a-37a5-467b-828e-9bae872781d4
      iscommand: false
      name: ""
      version: -1
    taskid: 576ef95a-37a5-467b-828e-9bae872781d4
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: RiskSense
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if RiskSense is enabled. Otherwise returns 'no'.
      id: d9274292-d91a-46fe-8c77-8f658406b37a
      iscommand: false
      name: Is RiskSense enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: d9274292-d91a-46fe-8c77-8f658406b37a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 195
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get list of ransomware and trending ransomware CVEs.
      id: 90ea1543-ba0c-4198-833f-be052b5e7678
      iscommand: false
      name: Get list of ransomware and trending ransomware CVEs
      type: title
      version: -1
    taskid: 90ea1543-ba0c-4198-833f-be052b5e7678
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 380
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      host_findings:
        simple: ${RiskSense.HostFinding}
      trending:
        simple: "False"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieve information of ransomware CVEs using the automation script
        and store it to context.
      id: 558b9015-315a-4967-8821-e4364e4cbc01
      iscommand: false
      name: Get ransomware CVEs
      script: RiskSenseGetRansomewareCVEScript
      type: regular
      version: -1
    taskid: 558b9015-315a-4967-8821-e4364e4cbc01
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 515
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      host_findings:
        simple: ${RiskSense.HostFinding}
      trending:
        simple: "True"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieve information regarding trending ransomware CVEs using the
        automation script and store it to context.
      id: 25963026-1c05-4ae0-88a2-bb9dc007c239
      iscommand: false
      name: Get trending ransomware CVEs
      script: RiskSenseGetRansomewareCVEScript
      type: regular
      version: -1
    taskid: 25963026-1c05-4ae0-88a2-bb9dc007c239
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 690
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get impacted assets
      id: 018e1d66-dc32-444f-8d07-e5df188e5c9c
      iscommand: false
      name: Get impacted assets
      type: title
      version: -1
    taskid: 018e1d66-dc32-444f-8d07-e5df188e5c9c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 865
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: RiskSense.RansomwareImpactedHosts=_embedded.hosts.id
      fieldname:
        simple: has_open_ransomware_finding
      operator:
        simple: EXACT
      size:
        simple: "1000"
      value:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets details of the supplied host. The host details can be searched
        based on input parameters like fieldname (Host Name, IP Address, Criticality,
        etc), operator (EXACT, IN, LIKE, BETWEEN), page, size, sort by, and sort direction.
      id: 780bc10c-263a-4b4d-8f35-67db071755aa
      iscommand: true
      name: Get impacted assets by ransomware CVEs
      script: '|||risksense-get-hosts'
      type: regular
      version: -1
    taskid: 780bc10c-263a-4b4d-8f35-67db071755aa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1010
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: RiskSense.TrendingRansomwareImpactedHosts=_embedded.hosts.id
      fieldname:
        simple: openRansomwareVulnLastTrendingOn
      operator:
        simple: BETWEEN
      size:
        simple: "1000"
      value:
        simple: ${Date.WeekAgoDate},${Date.CurrentDate}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets details of the supplied host. The host details can be searched
        based on input parameters like fieldname (Host Name, IP Address, Criticality,
        etc), operator (EXACT, IN, LIKE, BETWEEN), page, size, sort by, and sort direction.
      id: 28bba2a5-42d7-4f71-8257-1836d43be6fb
      iscommand: true
      name: Get impacted assets by trending ransomware CVEs
      script: '|||risksense-get-hosts'
      type: regular
      version: -1
    taskid: 28bba2a5-42d7-4f71-8257-1836d43be6fb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1010
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prepare graph
      id: 25563796-9d25-4daa-8d44-50b3600e5d16
      iscommand: false
      name: Prepare graph
      type: title
      version: -1
    taskid: 25563796-9d25-4daa-8d44-50b3600e5d16
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1185
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      CvesCount:
        complex:
          root: CVECount
      TrendingCvesCount:
        complex:
          root: TrendingCVECount
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Display chart based on CVEs and trending CVEs. '
      id: 45ca5ac4-ad19-4256-89ed-c6f0e434daa6
      iscommand: false
      name: Display chart based on counts of CVEs
      script: DisplayCVEChartScript
      type: regular
      version: -1
    taskid: 45ca5ac4-ad19-4256-89ed-c6f0e434daa6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1330
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0265609a-5ba2-4f6c-8c35-eb671fd1d923
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 0265609a-5ba2-4f6c-8c35-eb671fd1d923
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 30,
          "y": 1540
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_13_#default#": 0.88,
      "1_5_yes": 0.64
    },
    "paper": {
      "dimensions": {
        "height": 1555,
        "width": 830,
        "x": 30,
        "y": 50
      }
    }
  }
