contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.0.20
    packID: McAfee_Advanced_Threat_Defense
    packName: McAfee Advanced Threat Defense
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Detonates a File from a URL using the McAfee Advanced Threat Defense
  sandbox integration.
id: Detonate Remote File from URL - McAfee ATD
inputs:
- description: URL to detonate.
  key: URL
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Data
      root: URL
- description: Polling frequency - how often the polling command should run (minutes)
  key: Interval
  playbookInputQuery: null
  required: false
  value:
    simple: "1"
- description: How much time to wait before a timeout occurs (minutes)
  key: Timeout
  playbookInputQuery: null
  required: false
  value:
    simple: "15"
name: Detonate Remote File from URL - McAfee ATD
outputs:
- contextPath: ATD.Task.taskId
  description: The task ID of the sample uploaded
  type: string
- contextPath: ATD.Task.jobId
  description: The job ID of the sample uploaded
  type: string
- contextPath: ATD.Task.messageId
  description: The message Id relevant to the sample uploaded
  type: string
- contextPath: ATD.Task.url
  description: The URL detonated
  type: string
- contextPath: ATD.Task.srcIp
  description: Source IPv4 address
  type: string
- contextPath: ATD.Task.destIp
  description: Destination IPv4 address
  type: string
- contextPath: ATD.Task.MD5
  description: MD5 of the sample uploaded
  type: string
- contextPath: ATD.Task.SHA1
  description: SHA1 of the sample uploaded
  type: string
- contextPath: ATD.Task.SHA256
  description: SHA256 of the sample uploaded
  type: string
- contextPath: File.Name
  description: Filename (only in case of report type=json)
  type: string
- contextPath: File.Type
  description: File type e.g. "PE" (only in case of report type=json)
  type: string
- contextPath: File.MD5
  description: MD5 hash of the file (only in case of report type=json)
  type: string
- contextPath: File.SHA1
  description: SHA1 hash of the file (only in case of report type=json)
  type: string
- contextPath: File.SHA256
  description: SHA256 hash of the file (only in case of report type=json)
  type: string
- contextPath: File.EntryID
  description: The Entry ID of the sample
  type: string
- contextPath: DBotScore.Indicator
  description: The indicator we tested (only in case of report type=json)
  type: string
- contextPath: DBotScore.Type
  description: The type of the indicator (only in case of report type=json)
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score (only in case of report type=json)
  type: string
- contextPath: DBotScore.Score
  description: The actual score (only in case of report type=json)
  type: number
- contextPath: IP.Address
  description: IP's relevant to the sample
  type: string
- contextPath: InfoFile.EntryID
  description: The EntryID of the report file
  type: string
- contextPath: InfoFile.Extension
  description: The extension of the report file
  type: string
- contextPath: InfoFile.Name
  description: The name of the report file
  type: string
- contextPath: InfoFile.Info
  description: The info of the report file
  type: string
- contextPath: InfoFile.Size
  description: The size of the report file
  type: number
- contextPath: InfoFile.Type
  description: The type of the report file
  type: string
- contextPath: File
  description: File object
  type: unknown
- contextPath: File.Malicious
  description: File Malicious object
  type: unknown
- contextPath: DBotScore
  description: DBotScore object
  type: unknown
- contextPath: InfoFile
  description: Report file object
  type: unknown
- contextPath: URL.Malicious
  description: URL Malicious object
  type: unknown
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: start
      id: f2c37122-75bb-4405-80c6-34e8e972d224
      iscommand: false
      name: ""
      version: -1
    taskid: f2c37122-75bb-4405-80c6-34e8e972d224
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      submitType:
        simple: "3"
      url:
        complex:
          root: inputs.URL
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Uploads the submission to McAfee ATD.
      id: 6c62dcdb-e814-4ecb-8449-e6d02cfad409
      iscommand: true
      name: McAfee ATD Upload a File from a URL
      script: '|||atd-file-upload'
      type: regular
      version: -1
    taskid: 6c62dcdb-e814-4ecb-8449-e6d02cfad409
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 545
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        complex:
          accessor: Task
          filters:
          - - left:
                iscontext: true
                value:
                  simple: ATD.Task.taskId
              operator: isNotEqualNumber
              right:
                value:
                  simple: "-1"
          root: ATD
          transformers:
          - args:
              field:
                value:
                  simple: taskId
            operator: getField
      Interval:
        complex:
          root: inputs.Interval
      PollingCommandArgName:
        simple: taskId
      PollingCommandName:
        simple: atd-check-status
      Timeout:
        complex:
          root: inputs.Timeout
      dt:
        simple: ATD.Task(val.status != 'Completed').taskId
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 2af60cef-ae8f-45d0-88b6-ce81c990523c
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 2af60cef-ae8f-45d0-88b6-ce81c990523c
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      taskId:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: ATDTask.status
              operator: isEqualString
              right:
                value:
                  simple: Completed
          root: ATDTask
          transformers:
          - args:
              field:
                value:
                  simple: taskId
            operator: getField
      type:
        simple: pdf
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieve the reports from McAfee ATD.
      id: 61a895d1-e4d7-4c3a-8adc-83f6ee88f040
      iscommand: true
      name: McAfee ATD Get Report
      script: '|||atd-get-report'
      type: regular
      version: -1
    taskid: 61a895d1-e4d7-4c3a-8adc-83f6ee88f040
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1420
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.URL
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks that there is a URL in the playbook’s input.
      id: 06c9ca27-cfbc-41ab-805d-2091a2b9e210
      iscommand: false
      name: Is there a URL to detonate?
      type: condition
      version: -1
    taskid: 06c9ca27-cfbc-41ab-805d-2091a2b9e210
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Done
      id: b09656f6-45b8-4a84-872b-4f5b6c727291
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: b09656f6-45b8-4a84-872b-4f5b6c727291
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Task
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: ATD.Task.taskId
                    operator: isNotEqualNumber
                    right:
                      value:
                        simple: "-1"
                root: ATD
                transformers:
                - args:
                    field:
                      value:
                        simple: taskId
                  operator: getField
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks that valid URLs only have been sent to detonation.
      id: 4527bfbf-19ea-4c54-87e2-ccee19d7703d
      iscommand: false
      name: Filter taskId
      type: condition
      version: -1
    taskid: 4527bfbf-19ea-4c54-87e2-ccee19d7703d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 275,
          "y": 720
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: McAfee Advanced Threat Defense
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Verify that there is a valid instance of McAfee ATD enabled.
      id: 0e48dfeb-7b4f-4c39-8a77-610c2cbb8345
      iscommand: false
      name: Is McAfee ATD sandbox enabled?
      type: condition
      version: -1
    taskid: 0e48dfeb-7b4f-4c39-8a77-610c2cbb8345
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      taskId:
        complex:
          accessor: Task.taskId
          filters:
          - - left:
                iscontext: true
                value:
                  simple: ATD.Task.taskId
              operator: isNotEqualNumber
              right:
                value:
                  simple: "-1"
          root: ATD
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Updates the status of the tasks in the context.
      id: aafb15d2-bf2e-481a-8b3b-9e90f2c92d97
      iscommand: true
      name: atd-check-status
      script: '|||atd-check-status'
      type: regular
      version: -1
    taskid: aafb15d2-bf2e-481a-8b3b-9e90f2c92d97
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: ATDTask
      value:
        complex:
          accessor: Task
          filters:
          - - left:
                iscontext: true
                value:
                  simple: ATD.Task.taskId
              operator: isNotEqualNumber
              right:
                value:
                  simple: "-1"
          root: ATD
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: '-'
      id: a28f0313-4932-4d47-8dbf-bcbf98c11fdc
      iscommand: false
      name: Set Context
      script: Set
      type: regular
      version: -1
    taskid: a28f0313-4932-4d47-8dbf-bcbf98c11fdc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1245
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "8_2_yes": 0.57
    },
    "paper": {
      "dimensions": {
        "height": 1610,
        "width": 605,
        "x": 50,
        "y": 50
      }
    }
  }
