contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 1.0.7
    packID: SailPointIdentityIQ
    packName: SailPoint IdentityIQ
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Checks if the risk score of an identity exceeds a set threshold of 500
  and disables the accounts.
id: SailPoint IdentityIQ Disable User Account Access
inputs:
- description: Email of the Identity.
  key: email
  playbookInputQuery: null
  required: false
  value: {}
name: SailPoint IdentityIQ Disable User Account Access
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fe08bb86-e06f-4a0c-88c8-a3fbe2ae1f23
      iscommand: false
      name: ""
      version: -1
    taskid: fe08bb86-e06f-4a0c-88c8-a3fbe2ae1f23
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      email:
        simple: ${incident.details}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Search identities by search/filter parameters (id, email, risk
        & active) using IdentityIQ SCIM API's.
      id: d619c184-12aa-405c-877f-2e97db01875d
      iscommand: true
      name: Get Identities By Incident Details Email
      script: '|||identityiq-search-identities'
      type: regular
      version: -1
    taskid: d619c184-12aa-405c-877f-2e97db01875d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      identity_name:
        simple: ${IdentityIQ.Identity.userName}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Fetch accounts by search/filter parameters (id, display_name, last_refresh,
        native_identity, last_target_agg, identity_name & application_name) using
        IdentityIQ SCIM API's.
      id: 31a79536-3538-4fcd-8692-9e344ccee781
      iscommand: true
      name: Get Account
      script: '|||identityiq-get-accounts'
      type: regular
      version: -1
    taskid: 31a79536-3538-4fcd-8692-9e344ccee781
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: IdentityIQ.Identity.sailpointUser.riskScore
          operator: greaterThanOrEqual
          right:
            value:
              simple: "500"
      label: "yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: If Risk Greater Than 500
      id: 33a3d334-94c1-43b7-81c3-973ad4a73d2d
      iscommand: false
      name: If Risk Greater Than 500
      type: condition
      version: -1
    taskid: 33a3d334-94c1-43b7-81c3-973ad4a73d2d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Over 500
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 44abe31e-875a-43d7-8cc2-2ccaa9f6d64d
      iscommand: false
      name: High Risk (Risk higher than 500)
      script: Print
      type: regular
      version: -1
    taskid: 44abe31e-875a-43d7-8cc2-2ccaa9f6d64d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Less Risk User
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 7443cd86-3d21-4467-8a57-5707d946edec
      iscommand: false
      name: Low Risk (Risk lower than 500)
      script: Print
      type: regular
      version: -1
    taskid: 7443cd86-3d21-4467-8a57-5707d946edec
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      severity:
        simple: High
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 10df2814-9e78-4921-89ed-8321fbf98726
      iscommand: true
      name: Set Incident Severity To High
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 10df2814-9e78-4921-89ed-8321fbf98726
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 2a560618-b3e9-4203-8354-9e2c68ad0149
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 2a560618-b3e9-4203-8354-9e2c68ad0149
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1420
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Waiting For Manual Review For User Risk
      id: 282b63a5-d53d-4bd8-8481-5adeea9a3f78
      iscommand: false
      name: Waiting For Manual Review For User Risk
      type: regular
      version: -1
    taskid: 282b63a5-d53d-4bd8-8481-5adeea9a3f78
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: ${IdentityIQ.Account.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Disable account's active status by id using IdentityIQ SCIM API's.
      id: a0ffa275-3e22-46e7-82d1-f66758b5d0ce
      iscommand: true
      name: Disable Account
      script: '|||identityiq-disable-account'
      type: regular
      version: -1
    taskid: a0ffa275-3e22-46e7-82d1-f66758b5d0ce
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1465,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
