contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.0.0
    packID: Cybereason
    packName: Cybereason
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook isolates a machine based on the hostname provided.
id: Isolate Endpoint - Cybereason
inputs:
- description: The hostname of the endpoint to isolate using Cybereason.
  key: Hostname
  playbookInputQuery: null
  required: false
  value: {}
name: Isolate Endpoint - Cybereason
outputs:
- contextPath: Cybereason.Machine
  description: Machine name.
- contextPath: Cybereason.IsIsolated
  description: Is the machine isolated.
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7b50bf9c-8ba7-412d-8901-3bcacfbe655f
      iscommand: false
      name: ""
      version: -1
    taskid: 7b50bf9c-8ba7-412d-8901-3bcacfbe655f
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -40
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Cybereason
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Check if the Cybereason integration is enabled.
      id: 71221472-29d2-482b-8272-5a226ebf8d16
      iscommand: false
      name: Is Cybereason integration enabled?
      type: condition
      version: -1
    taskid: 71221472-29d2-482b-8272-5a226ebf8d16
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 130
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Hostname
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether there is an endpoint to isolate.
      id: f9d63cb1-e655-4c14-8c4f-3c53d5bf3bd6
      iscommand: false
      name: Is there an endpoint to isolate?
      type: condition
      version: -1
    taskid: f9d63cb1-e655-4c14-8c4f-3c53d5bf3bd6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 690,
          "y": 320
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      machine:
        complex:
          root: inputs.Hostname
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Isolates a machine that has been infected from the rest of the
        network.
      id: 72580fee-68d4-40f6-88d8-f1a17877e084
      iscommand: true
      name: Isolate endpoint
      script: '|||cybereason-isolate-machine'
      type: regular
      version: -1
    taskid: 72580fee-68d4-40f6-88d8-f1a17877e084
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 920,
          "y": 940
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 641d5d3f-d8f4-4117-8121-0d2a40f1f542
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 641d5d3f-d8f4-4117-8121-0d2a40f1f542
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1110
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      machine:
        simple: ${inputs.Hostname}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the machine is currently connected to the Cybereason
        server.
      id: b6d17961-11e6-4588-8f3d-ec1024925529
      iscommand: true
      name: check if endpoint is online
      script: '|||cybereason-is-probe-connected'
      type: regular
      version: -1
    taskid: b6d17961-11e6-4588-8f3d-ec1024925529
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 920,
          "y": 550
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Cybereason.Machine.isConnected
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: "yes"
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8f8bc72b-12db-4350-8825-bf8e39e32eba
      iscommand: false
      name: Is the endpoint online?
      type: condition
      version: -1
    taskid: 8f8bc72b-12db-4350-8825-bf8e39e32eba
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 920,
          "y": 710
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_2_yes": 0.32,
      "1_4_#default#": 0.17,
      "2_4_#default#": 0.19,
      "6_4_#default#": 0.55
    },
    "paper": {
      "dimensions": {
        "height": 1215,
        "width": 850,
        "x": 450,
        "y": -40
      }
    }
  }
